/**
 * telegram-mint-bot.js  —  Robinhood Chain
 *
 * Combines watch-and-mint.js's detection + copy-mint pipeline with:
 *   - Telegram notifications: posts when a watched wallet mints, and
 *     again when this bot successfully copies that mint
 *   - Telegram commands to manage the watched-wallet list, backed by
 *     Supabase instead of a static .env value:
 *       /addwallet 0x...      add a wallet to watch
 *       /removewallet 0x...   stop watching a wallet
 *       /wallets              list all watched wallets + how many
 *       /status               show DRY_RUN state and poll interval
 *       /help                 list commands
 *
 * CHANGES IN THIS VERSION (debugging a "silent hang" on startup):
 *   1. Startup checkpoint logs — every await in main() now logs before
 *      and after, so a hang shows you exactly which call never returns
 *      instead of just staring at a blank terminal.
 *   2. Network timeouts everywhere — Supabase client, OpenSea fetch,
 *      Blockscout fetch, and the ethers RPC providers all now have an
 *      explicit timeout (8-12s) instead of Node's default of "forever".
 *      A hung dependency now fails loud instead of hanging silent.
 *   3. Global unhandledRejection / uncaughtException handlers — so a
 *      promise rejection that used to vanish now prints a stack trace.
 *   4. PRIVATE_KEY format validation — previously an empty string or a
 *      malformed key only surfaced as an opaque ethers error deep in
 *      Wallet construction. Now checked up front with a clear message.
 *
 * WHY SUPABASE INSTEAD OF WATCHED_WALLETS IN .env:
 * .env is static — changing it means editing a file and restarting the
 * process. Storing the wallet list in Supabase means /addwallet from
 * Telegram takes effect on the very next poll cycle, no restart needed.
 * The bot re-reads the table from Supabase every WALLET_REFRESH_MS.
 *
 * SUPABASE TABLE (run once in the Supabase SQL editor):
 *   create table watched_wallets (
 *     id bigint generated by default as identity primary key,
 *     address text unique not null,
 *     added_at timestamptz default now()
 *   );
 *
 * MINTING LOGIC — unchanged from watch-and-mint.js:
 *   1. Detect a Transfer(0x0 -> watched wallet) on Robinhood Chain
 *   2. Resolve the contract to an OpenSea collection, mint via the
 *      Drops API (POST /drops/{slug}/mint)
 *   3. If there's no OpenSea Drop for it, fall back to a verified ABI
 *      from Blockscout and a short list of common mint() signatures
 *   See watch-and-mint.js's file header for the full rationale on both.
 *
 * SAFETY DEFAULT: DRY_RUN=true — logs/notifies what WOULD happen without
 * broadcasting any transaction. Flip to false only after confirming
 * detection + Telegram notifications both work correctly.
 *
 * .env required:
 *   TELEGRAM_BOT_TOKEN=...        from @BotFather
 *   TELEGRAM_CHAT_ID=...          chat/group/channel id to post alerts to
 *   SUPABASE_URL=...
 *   SUPABASE_KEY=...              service_role or anon key with table access
 *   RPC_URLS=...                  comma-separated Robinhood Chain RPCs
 *   OPENSEA_API_KEY=...
 *   PRIVATE_KEY=...               required unless DRY_RUN=true
 *   WALLET_ADDRESS=...            your minting wallet — must match PRIVATE_KEY
 *
 * npm i telegraf @supabase/supabase-js ethers dotenv node-fetch
 * node telegram-mint-bot.js
 */

import 'dotenv/config';
import { Telegraf, Markup } from 'telegraf';
import { createClient } from '@supabase/supabase-js';
import { ethers } from 'ethers';
import fetch from 'node-fetch';

// ---------------------------------------------------------------------------
// Global error visibility — nothing should ever fail silently again
// ---------------------------------------------------------------------------

process.on('unhandledRejection', (reason) => {
  console.error('[unhandledRejection]', reason);
});
process.on('uncaughtException', (err) => {
  console.error('[uncaughtException]', err);
});

// ---------------------------------------------------------------------------
// Small helper: fetch with a hard timeout, so a hung dependency fails
// loud instead of hanging the whole process forever.
// ---------------------------------------------------------------------------

function fetchWithTimeout(url, options = {}, timeoutMs = 10000) {
  const controller = new AbortController();
  const id = setTimeout(() => controller.abort(), timeoutMs);
  return fetch(url, { ...options, signal: controller.signal }).finally(() => clearTimeout(id));
}

// Telegram's legacy "Markdown" parse mode breaks on any unmatched _ * ` [ ] —
// which is very easy to hit by accident (e.g. "DRY_RUN", an error message,
// or an OpenSea slug with an underscore in it). HTML parse mode only cares
// about actual tags, so it's far more robust — but any dynamic text placed
// inside a tag still needs escaping so a literal "<" or "&" doesn't break it.
function escapeHtml(str) {
  return String(str)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;');
}

async function withTimeout(promise, timeoutMs, label) {
  let timer;
  const timeout = new Promise((_, reject) => {
    timer = setTimeout(() => reject(new Error(`[timeout] ${label} took longer than ${timeoutMs}ms`)), timeoutMs);
  });
  try {
    return await Promise.race([promise, timeout]);
  } finally {
    clearTimeout(timer);
  }
}

// ---------------------------------------------------------------------------
// Config
// ---------------------------------------------------------------------------

const TELEGRAM_BOT_TOKEN = process.env.TELEGRAM_BOT_TOKEN || '';
const TELEGRAM_CHAT_ID = process.env.TELEGRAM_CHAT_ID || '';
const SUPABASE_URL = process.env.SUPABASE_URL || '';
const SUPABASE_KEY = process.env.SUPABASE_KEY || '';
const WALLETS_TABLE = process.env.WALLETS_TABLE || 'watched_wallets';

const RPC_URLS = (process.env.RPC_URLS || '')
  .split(',')
  .map((s) => s.trim())
  .filter(Boolean);

const CHAIN_ID = Number(process.env.CHAIN_ID || 4663); // 4663 mainnet, 46630 testnet
const OPENSEA_CHAIN_SLUG = process.env.OPENSEA_CHAIN_SLUG || 'robinhood';
const OPENSEA_API_KEY = process.env.OPENSEA_API_KEY || '';
const PRIVATE_KEY_RAW = (process.env.PRIVATE_KEY || '').trim();
const WALLET_ADDRESS = (process.env.WALLET_ADDRESS || '').toLowerCase();
const DRY_RUN = (process.env.DRY_RUN || 'true').toLowerCase() !== 'false';
const POLL_INTERVAL_MS = Number(process.env.POLL_INTERVAL_MS || 1000);
const WALLET_REFRESH_MS = Number(process.env.WALLET_REFRESH_MS || 5000);
const MINT_QUANTITY = Number(process.env.MINT_QUANTITY || 1);
const MAX_PRICE_ETH =
  process.env.MAX_PRICE_ETH === undefined || process.env.MAX_PRICE_ETH.trim() === ''
    ? null
    : Number(process.env.MAX_PRICE_ETH);

const EXPLORER_API_BASE = process.env.EXPLORER_API_BASE || 'https://api.blockscout.com/4663/api/v2';
const EXPLORER_API_KEY = process.env.EXPLORER_API_KEY || '';

if (!TELEGRAM_BOT_TOKEN) throw new Error('Set TELEGRAM_BOT_TOKEN in .env.');
if (!TELEGRAM_CHAT_ID) throw new Error('Set TELEGRAM_CHAT_ID in .env.');
if (!SUPABASE_URL || !SUPABASE_KEY) throw new Error('Set SUPABASE_URL and SUPABASE_KEY in .env.');
if (RPC_URLS.length === 0) throw new Error('Set RPC_URLS in .env.');
if (!OPENSEA_API_KEY) throw new Error('Set OPENSEA_API_KEY in .env.');

// Normalize + validate the private key format up front, with a clear
// message, instead of letting ethers.Wallet() throw an opaque error later.
let PRIVATE_KEY = '';
if (!DRY_RUN) {
  if (!PRIVATE_KEY_RAW || !WALLET_ADDRESS) {
    throw new Error('PRIVATE_KEY and WALLET_ADDRESS are required in .env unless DRY_RUN=true.');
  }
  PRIVATE_KEY = PRIVATE_KEY_RAW.startsWith('0x') ? PRIVATE_KEY_RAW : `0x${PRIVATE_KEY_RAW}`;
  if (!/^0x[0-9a-fA-F]{64}$/.test(PRIVATE_KEY)) {
    throw new Error(
      'PRIVATE_KEY in .env is not a valid 32-byte hex key (expected 64 hex chars, optionally prefixed with 0x). ' +
        'Check for stray whitespace, placeholder text, or a truncated paste.'
    );
  }
  if (!ethers.isAddress(WALLET_ADDRESS)) {
    throw new Error(`WALLET_ADDRESS in .env ("${WALLET_ADDRESS}") is not a valid address.`);
  }
}

// ===== MULTI-CHAIN FOUNDATION (Stage 1) =====
const RH_ENABLED = (process.env.RH_ENABLED || 'true').toLowerCase() !== 'false';
const ETH_ENABLED = (process.env.ETH_ENABLED || 'false').toLowerCase() === 'true';

const RH_MAX_PRICE_ETH =
  process.env.RH_MAX_PRICE_ETH === undefined || String(process.env.RH_MAX_PRICE_ETH).trim() === ''
    ? MAX_PRICE_ETH
    : Number(process.env.RH_MAX_PRICE_ETH);

const ETH_MAX_PRICE_ETH =
  process.env.ETH_MAX_PRICE_ETH === undefined || String(process.env.ETH_MAX_PRICE_ETH).trim() === ''
    ? MAX_PRICE_ETH
    : Number(process.env.ETH_MAX_PRICE_ETH);

const RH_DRY_RUN = (process.env.RH_DRY_RUN || (DRY_RUN ? 'true' : 'false')).toLowerCase() !== 'false';
const ETH_DRY_RUN = (process.env.ETH_DRY_RUN || (DRY_RUN ? 'true' : 'false')).toLowerCase() !== 'false';

const chainConfigs = {
  robinhood: {
    name: 'robinhood',
    enabled: RH_ENABLED,
    chainId: Number(process.env.RH_CHAIN_ID || CHAIN_ID || 4663),
    rpcUrls: (process.env.RH_RPC_URLS || process.env.RPC_URLS || '')
      .split(',')
      .map(s => s.trim())
      .filter(Boolean),
    openseaSlug: process.env.RH_OPENSEA_SLUG || process.env.OPENSEA_CHAIN_SLUG || 'robinhood',
    explorerApiBase: process.env.RH_EXPLORER_API_BASE || EXPLORER_API_BASE,
    explorerApiKey: process.env.RH_EXPLORER_API_KEY || EXPLORER_API_KEY || '',
    maxPriceEth: RH_MAX_PRICE_ETH,
    dryRun: RH_DRY_RUN,
  },
  ethereum: {
    name: 'ethereum',
    enabled: ETH_ENABLED,
    chainId: Number(process.env.ETH_CHAIN_ID || 1),
    rpcUrls: (process.env.ETH_RPC_URLS || '')
      .split(',')
      .map(s => s.trim())
      .filter(Boolean),
    openseaSlug: process.env.ETH_OPENSEA_SLUG || 'ethereum',
    explorerApiBase: process.env.ETH_EXPLORER_API_BASE || 'https://api.etherscan.io/api',
    explorerApiKey: process.env.ETH_EXPLORER_API_KEY || '',
    maxPriceEth: ETH_MAX_PRICE_ETH,
    dryRun: ETH_DRY_RUN,
  },
  arc: {
    name: 'arc',
    enabled: (process.env.ARC_ENABLED || 'false').toLowerCase() === 'true',
    chainId: Number(process.env.ARC_CHAIN_ID || 5042),
    rpcUrls: (process.env.ARC_RPC_URLS || 'https://rpc.mainnet.arc.io')
      .split(',')
      .map(s => s.trim())
      .filter(Boolean),
    openseaSlug: process.env.ARC_OPENSEA_SLUG || 'arc',
    explorerApiBase: process.env.ARC_EXPLORER_API_BASE || 'https://explorer.arc.io/api',
    explorerApiKey: process.env.ARC_EXPLORER_API_KEY || '',
    maxPriceEth:
      process.env.ARC_MAX_PRICE_ETH === undefined || String(process.env.ARC_MAX_PRICE_ETH).trim() === ''
        ? null
        : Number(process.env.ARC_MAX_PRICE_ETH),
    dryRun: (process.env.ARC_DRY_RUN || 'true').toLowerCase() !== 'false',
  },
    ink: {
    name: 'ink',
    enabled: (process.env.INK_ENABLED || 'false').toLowerCase() === 'true',
    chainId: Number(process.env.INK_CHAIN_ID || 57073),
    rpcUrls: (process.env.INK_RPC_URLS || '')
      .split(',')
      .map(s => s.trim())
      .filter(Boolean),
    openseaSlug: process.env.INK_OPENSEA_SLUG || 'ink',
    explorerApiBase: process.env.INK_EXPLORER_API_BASE || 'https://explorer.inkonchain.com/api',
    explorerApiKey: process.env.INK_EXPLORER_API_KEY || '',
    maxPriceEth:
      process.env.INK_MAX_PRICE_ETH === undefined || String(process.env.INK_MAX_PRICE_ETH).trim() === ''
        ? 0
        : Number(process.env.INK_MAX_PRICE_ETH),
    dryRun: (process.env.INK_DRY_RUN || 'true').toLowerCase() !== 'false',
  }
};

console.log('[chains] Robinhood enabled:', chainConfigs.robinhood.enabled, 'RPCs:', chainConfigs.robinhood.rpcUrls.length);
console.log('[chains] Ethereum enabled:', chainConfigs.ethereum.enabled, 'RPCs:', chainConfigs.ethereum.rpcUrls.length);
console.log('[chains] ARC enabled:', chainConfigs.arc.enabled, 'RPCs:', chainConfigs.arc.rpcUrls.length);
console.log('[chains] Ink enabled:', chainConfigs.ink.enabled, 'RPCs:', chainConfigs.ink.rpcUrls.length);

if (chainConfigs.ethereum.enabled && chainConfigs.ethereum.rpcUrls.length === 0) {
  console.warn('[chains] ETH_ENABLED=true but ETH_RPC_URLS is empty');
}
// ===== END MULTI-CHAIN FOUNDATION =====

const NULL_ADDRESS = '0x0000000000000000000000000000000000000000';
const ERC721_TRANSFER_TOPIC = ethers.id('Transfer(address,address,uint256)');
const OPENSEA_BASE = 'https://api.opensea.io/api/v2';

const COMMON_MINT_ABIS = [
  'function mint() public payable',
  'function mint(uint256 quantity) public payable',
  'function mint(address to, uint256 quantity) public payable',
  'function publicMint(uint256 quantity) public payable',
  'function claim(uint256 quantity) public payable',
];

// ---------------------------------------------------------------------------
// Supabase — watched wallet list
// ---------------------------------------------------------------------------

const supabase = createClient(SUPABASE_URL, SUPABASE_KEY, {
  global: { fetch: (url, options) => fetchWithTimeout(url, options, 10000) },
});

async function dbListWallets() {
  const { data, error } = await supabase.from(WALLETS_TABLE).select('address').order('added_at', { ascending: true });
  if (error) throw new Error(`Supabase select failed: ${error.message}`);
  return data.map((row) => row.address.toLowerCase());
}

async function dbAddWallet(address) {
  const { error } = await supabase.from(WALLETS_TABLE).insert([{ address: address.toLowerCase() }]).select();
  if (error) {
    if (error.code === '23505') return { added: false, reason: 'already watched' }; // unique violation
    throw new Error(`Supabase insert failed: ${error.message}`);
  }
  return { added: true };
}

async function dbRemoveWallet(address) {
  const { data, error } = await supabase
    .from(WALLETS_TABLE)
    .delete()
    .eq('address', address.toLowerCase())
    .select();
  if (error) throw new Error(`Supabase delete failed: ${error.message}`);
  return data.length > 0;
}

// In-memory cache, refreshed on a timer so /addwallet takes effect without
// a restart, but the hot poll loop doesn't hit Supabase every second.
let watchedWallets = [];
let isPaused = false;   // when true, bot detects but does not mint
let isRhPaused = false;
let isEthPaused = false;
let isInkPaused = false;
let isArcPaused = false;


// Telegram interactive flows
let pendingFundGas = null;   // null | { step, chain? }
let pendingCollect = null;   // null | { step, chain?, contract?, to? }
let pendingOffers = null;    // null | { step, chain?, contract?, min? }
let pendingAcceptOffers = null; // null | { matches: [...], chainKey, contract }

// ===== Stats + already-minted protection =====
// Track successful mints per contract+wallet so failed wallets can retry later
// key format: `${contractLower}:${walletLower}`
const successfulMints = new Set();
const dailyStats = {
  detected: 0,
  attempted: 0,
  success: 0,
  failed: 0,
  skipped: 0,
  startedAt: Date.now(),
};

function todayUtcDate() {
  return new Date().toISOString().slice(0, 10); // YYYY-MM-DD UTC
}

function resetDailyStats() {
  dailyStats.detected = 0;
  dailyStats.attempted = 0;
  dailyStats.success = 0;
  dailyStats.failed = 0;
  dailyStats.skipped = 0;
  dailyStats.startedAt = Date.now();
}

async function loadDailyStats() {
  const day = todayUtcDate();
  try {
    const { data, error } = await supabase
      .from('bot_daily_stats')
      .select('*')
      .eq('day', day)
      .maybeSingle();

    if (error) throw error;

    if (data) {
      dailyStats.detected = data.detected || 0;
      dailyStats.attempted = data.attempted || 0;
      dailyStats.success = data.success || 0;
      dailyStats.failed = data.failed || 0;
      dailyStats.skipped = data.skipped || 0;
      console.log(`[stats] loaded today ${day}:`, {
        detected: dailyStats.detected,
        attempted: dailyStats.attempted,
        success: dailyStats.success,
        failed: dailyStats.failed,
        skipped: dailyStats.skipped,
      });
    } else {
      resetDailyStats();
      console.log(`[stats] no row for ${day}, starting fresh`);
    }
  } catch (err) {
    console.error(`[stats] load failed: ${err.message}`);
  }
}

async function saveDailyStats() {
  const day = todayUtcDate();
  try {
    const { error } = await supabase.from('bot_daily_stats').upsert({
      day,
      detected: dailyStats.detected,
      attempted: dailyStats.attempted,
      success: dailyStats.success,
      failed: dailyStats.failed,
      skipped: dailyStats.skipped,
      updated_at: new Date().toISOString(),
    });
    if (error) throw error;
  } catch (err) {
    console.error(`[stats] save failed: ${err.message}`);
  }
}
// ===== End stats =====

async function refreshWatchedWallets() {
  try {
    watchedWallets = await dbListWallets();
  } catch (err) {
    console.error(`[supabase] failed to refresh wallet list: ${err.message}`);
  }
}

// ---------------------------------------------------------------------------
// Telegram
// ---------------------------------------------------------------------------

const bot = new Telegraf(TELEGRAM_BOT_TOKEN);

function isAuthorizedChat(ctx) {
  return String(ctx.chat.id) === String(TELEGRAM_CHAT_ID);
}

async function notify(text) {
  try {
    await bot.telegram.sendMessage(TELEGRAM_CHAT_ID, text, { parse_mode: 'HTML', disable_web_page_preview: true });
  } catch (err) {
    console.error(`[telegram] failed to send message: ${err.message}`);
  }
}

function getChainRpcPool(chainKey) {
  const key = String(chainKey || '').toLowerCase();
  if (key === 'eth' || key === 'ethereum') {
    if (!ethRpcPool) throw new Error('Ethereum RPC not ready');
    return { pool: ethRpcPool, label: 'Ethereum', openseaSlug: chainConfigs.ethereum.openseaSlug || 'ethereum' };
  }
  if (key === 'ink') {
    if (!inkRpcPool) throw new Error('Ink RPC not ready');
    return { pool: inkRpcPool, label: 'Ink', openseaSlug: chainConfigs.ink.openseaSlug || 'ink' };
  }
  if (key === 'arc') {
    if (!arcRpcPool) throw new Error('Arc RPC not ready');
    return { pool: arcRpcPool, label: 'Arc', openseaSlug: chainConfigs.arc.openseaSlug || 'arc' };
  }
  return {
    pool: rpcPool,
    label: 'Robinhood',
    openseaSlug: chainConfigs.robinhood.openseaSlug || 'robinhood',
  };
}

async function getEthPriceUsd() {
  // Free public price feed (no key)
  const url = 'https://api.coingecko.com/api/v3/simple/price?ids=ethereum&vs_currencies=usd';
  const res = await fetchWithTimeout(url, {}, 8000);
  if (!res.ok) throw new Error(`Price API HTTP ${res.status}`);
  const data = await res.json();
  const price = Number(data?.ethereum?.usd);
  if (!Number.isFinite(price) || price <= 0) throw new Error('Invalid ETH price');
  return price;
}

function parseFundAmount(amountStr, chainKey) {
  const raw = String(amountStr || '').trim().toLowerCase();
  if (!raw) throw new Error('empty');

  // $3 / 3$ / 3usd / usd3
  const usdMatch =
    raw.match(/^\$\s*([0-9]*\.?[0-9]+)$/) ||
    raw.match(/^([0-9]*\.?[0-9]+)\s*\$$/) ||
    raw.match(/^([0-9]*\.?[0-9]+)\s*usd$/) ||
    raw.match(/^usd\s*([0-9]*\.?[0-9]+)$/);

  if (usdMatch) {
    const usd = Number(usdMatch[1]);
    if (!Number.isFinite(usd) || usd <= 0) throw new Error('bad usd');
    return { type: 'usd', usd };
  }

  // plain number = native token amount (ETH or USDC on Arc)
  const native = Number(raw);
  if (!Number.isFinite(native) || native <= 0) throw new Error('bad amount');
  return { type: 'native', amount: native };
}

function parseChainKey(text) {
  const t = String(text || '').trim().toLowerCase();
  if (t === 'rh' || t === 'robinhood') return 'rh';
  if (t === 'eth' || t === 'ethereum') return 'eth';
  if (t === 'ink') return 'ink';
  if (t === 'arc') return 'arc';
  return null;
}

async function runFundGas(ctx, amountStr, chainKey = 'rh') {
  try {
    if (!sponsorWallet) {
      return ctx.reply('❌ No sponsor/funder wallet configured.');
    }
    if (!wallets || wallets.length === 0) {
      return ctx.reply('❌ No minting wallets loaded.');
    }

    const { pool, label } = getChainRpcPool(chainKey);
    const isArc = String(chainKey).toLowerCase() === 'arc';
    const tokenName = isArc ? 'USDC' : 'ETH';

    let amountEth; // native amount to send (ETH or USDC units)
    let usdNote = '';

    try {
      const parsed = parseFundAmount(amountStr, chainKey);

      if (parsed.type === 'usd') {
        if (isArc) {
          // Arc native gas token is USDC ≈ $1
          amountEth = parsed.usd;
          usdNote = ` (≈ $${parsed.usd} USDC)`;
        } else {
          const ethPrice = await getEthPriceUsd();
          amountEth = parsed.usd / ethPrice;
          usdNote = ` ($${parsed.usd} ≈ ${amountEth.toFixed(6)} ETH @ $${ethPrice.toFixed(2)})`;
        }
      } else {
        amountEth = parsed.amount;
      }

      if (!Number.isFinite(amountEth) || amountEth <= 0) throw new Error('bad amount');
    } catch (err) {
      return ctx.reply(
        '❌ Invalid amount.\n\n' +
        'Examples:\n' +
        '• <code>0.002</code> (native)\n' +
        '• <code>$3</code> (dollars)\n' +
        '• <code>3usd</code>\n\n' +
        `Error: ${escapeHtml(err.message)}`,
        { parse_mode: 'HTML' }
      );
    }

    // safety cap for accidental huge USD → ETH conversions
    if (!isArc && amountEth > 0.2) {
      return ctx.reply(
        `❌ Amount too high for safety: <b>${amountEth.toFixed(6)} ETH</b>${usdNote}\n` +
        `Max allowed per wallet: 0.2 ETH. Try a smaller $ amount.`,
        { parse_mode: 'HTML' }
      );
    }

    const amountWei = ethers.parseEther(String(amountEth));
    const totalNeeded = amountWei * BigInt(wallets.length);
    const provider = pool.current();
    const funder = sponsorWallet.signer.connect(provider);

    const balance = await provider.getBalance(sponsorWallet.address);
    if (balance < totalNeeded) {
      return ctx.reply(
        `❌ Funder balance too low on ${label}.\n` +
        `Need at least ~${ethers.formatEther(totalNeeded)} ${tokenName} for transfers (plus gas).\n` +
        `Funder balance: ${ethers.formatEther(balance)} ${tokenName}`
      );
    }

    await ctx.reply(
      `⛽ Sending <b>${Number(amountEth).toFixed(6)}</b> ${tokenName} on <b>${label}</b> to <b>${wallets.length}</b> wallets...${usdNote}\n` +
      `From: <code>${escapeHtml(sponsorWallet.address.slice(0, 12))}...</code>`,
      { parse_mode: 'HTML' }
    );

    const results = [];
    let successCount = 0;

    for (const w of wallets) {
      try {
        const tx = await funder.sendTransaction({
          to: w.address,
          value: amountWei,
        });
        await tx.wait();
        successCount += 1;
        results.push(`✅ ${w.address.slice(0, 10)}... ${amountEth} ${tokenName} | ${tx.hash.slice(0, 12)}...`);
      } catch (err) {
        results.push(`❌ ${w.address.slice(0, 10)}... ${(err.message || 'failed').slice(0, 80)}`);
      }
    }

    await ctx.reply(
      `⛽ <b>Fund Gas result</b> (${label})\n` +
      `Success: <b>${successCount}/${wallets.length}</b>\n\n` +
      results.join('\n'),
      { parse_mode: 'HTML' }
    );
  } catch (err) {
    await ctx.reply(`❌ Fund gas failed: ${err.message}`);
  }
}

const ERC721_ABI = [
  'function ownerOf(uint256 tokenId) view returns (address)',
  'function balanceOf(address owner) view returns (uint256)',
  'function tokenOfOwnerByIndex(address owner, uint256 index) view returns (uint256)',
  'function safeTransferFrom(address from, address to, uint256 tokenId)',
  'function transferFrom(address from, address to, uint256 tokenId)',
];

function parsePriceInput(str) {
  const raw = String(str || '').trim().toLowerCase();
  if (!raw || raw === 'none' || raw === '-') return null;

  const usdMatch =
    raw.match(/^\$\s*([0-9]*\.?[0-9]+)$/) ||
    raw.match(/^([0-9]*\.?[0-9]+)\s*\$$/) ||
    raw.match(/^([0-9]*\.?[0-9]+)\s*usd$/);

  if (usdMatch) {
    const usd = Number(usdMatch[1]);
    if (!Number.isFinite(usd) || usd < 0) throw new Error('bad usd price');
    return { kind: 'usd', value: usd };
  }

  const native = Number(raw);
  if (!Number.isFinite(native) || native < 0) throw new Error('bad price');
  return { kind: 'native', value: native };
}

function offerPriceToNativeAndUsd(offer) {
  if (!offer || typeof offer !== 'object') return null;

  const price = offer.price || offer.current_price || {};
  const currency = String(
    price.currency ||
    price.payment_token?.symbol ||
    offer.payment_token?.symbol ||
    'ETH'
  ).toUpperCase();

  const decimals = Number(
    price.decimals ??
    price.payment_token?.decimals ??
    offer.payment_token?.decimals ??
    18
  );

  // Common OpenSea shapes
  let raw =
    price.value ??
    price.current_price ??
    price.amount ??
    offer.current_price ??
    offer.amount ??
    null;

  // Sometimes nested as { value: { raw/value } }
  if (raw && typeof raw === 'object') {
    raw = raw.raw ?? raw.value ?? raw.amount ?? null;
  }

  // Seaport protocol_data fallback (sum of offer item startAmounts is not ideal;
  // for standard ETH/WETH offers, consideration often holds payment — skip if messy)
  if (raw == null && offer.protocol_data?.parameters) {
    const params = offer.protocol_data.parameters;
    const consideration = params.consideration || [];
    // For an offer, the buyer offers payment tokens in "offer" array
    const offerItems = params.offer || [];
    const paymentItem =
      offerItems.find((i) => String(i.itemType) === '1' || i.itemType === 1) ||
      offerItems[0];
    if (paymentItem?.startAmount) raw = paymentItem.startAmount;
  }

  if (raw == null) return null;

  let native = NaN;
  if (typeof raw === 'string') {
    if (/^\d+$/.test(raw)) {
      // integer wei-like
      try {
        native = Number(ethers.formatUnits(raw, decimals));
      } catch {
        native = Number(raw);
      }
    } else {
      native = Number(raw);
    }
  } else if (typeof raw === 'number') {
    // large number likely wei
    if (raw > 1e10) {
      try {
        native = Number(ethers.formatUnits(BigInt(Math.trunc(raw)), decimals));
      } catch {
        native = raw;
      }
    } else {
      native = raw;
    }
  } else if (typeof raw === 'bigint') {
    native = Number(ethers.formatUnits(raw, decimals));
  }

  if (!Number.isFinite(native) || native < 0) return null;

  const usd =
    price.usd != null ? Number(price.usd) :
    price.value_usd != null ? Number(price.value_usd) :
    offer.price?.usd != null ? Number(offer.price.usd) :
    null;

  return {
    native,
    usd: Number.isFinite(usd) ? usd : null,
    currency,
    raw: String(raw),
  };
}

function openseaChainName(chainKey) {
  const k = String(chainKey || '').toLowerCase();
  if (k === 'eth' || k === 'ethereum') return 'ethereum';
  if (k === 'ink') return 'ink';
  if (k === 'arc') return 'arc';
  return 'robinhood';
}

async function runAcceptOffers(ctx, payload) {
  try {
    const { matches, chainKey, contract, slug } = payload;
    const { pool, label } = getChainRpcPool(chainKey);
    const provider = pool.current();
    const chainName = openseaChainName(chainKey);
    const results = [];

    await ctx.reply(
      `💸 Accepting <b>${matches.length}</b> offer(s) on <b>${label}</b>...\n` +
      `Collection: <code>${escapeHtml(slug)}</code>`,
      { parse_mode: 'HTML' }
    );

    for (const m of matches) {
      try {
        if (!m.orderHash) {
          results.push(`❌ #${m.tokenId} missing order hash`);
          continue;
        }

        // OpenSea fulfillment data for accepting an offer (seller side)
        const body = {
          offer: {
            hash: m.orderHash,
            chain: chainName,
            protocol_address: m.protocolAddress,
          },
          fulfiller: {
            address: m.wallet.address,
          },
          consideration: {
            asset_contract_address: contract,
            token_id: m.tokenId,
          },
        };

        const fulfill = await openseaFetch('/offers/fulfillment_data', {
          method: 'POST',
          body,
        });

        // Response shapes vary; try common paths
        const txData =
          fulfill?.fulfillment_data?.transaction ||
          fulfill?.transaction ||
          fulfill?.actions?.[0]?.transaction ||
          null;

        const to =
          txData?.to ||
          txData?.target ||
          fulfill?.to ||
          m.protocolAddress;
        const data =
          txData?.data ||
          txData?.input_data ||
          txData?.calldata ||
          fulfill?.data;
        const value = BigInt(txData?.value || fulfill?.value || '0');

        if (!to || !data) {
          results.push(
            `❌ ${m.wallet.address.slice(0, 10)}... #${m.tokenId} no fulfillment tx data`
          );
          continue;
        }

        const signer = m.wallet.signer.connect(provider);
        const tx = await signer.sendTransaction({ to, data, value });
        const receipt = await tx.wait();

        if (receipt.status === 1) {
          results.push(
            `✅ ${m.wallet.address.slice(0, 10)}... #${m.tokenId} accepted | ${tx.hash.slice(0, 12)}...`
          );
        } else {
          results.push(`❌ ${m.wallet.address.slice(0, 10)}... #${m.tokenId} reverted`);
        }
      } catch (err) {
        results.push(
          `❌ ${m.wallet?.address?.slice(0, 10) || '?'}... #${m.tokenId} → ${(err.message || 'failed').slice(0, 80)}`
        );
      }
    }

    await ctx.reply(
      `💸 <b>Accept result</b> (${label})\n\n` + results.join('\n'),
      { parse_mode: 'HTML' }
    );
  } catch (err) {
    await ctx.reply(`❌ Accept failed: ${err.message}`);
  }
}

async function runListOffers(ctx, chainKey, contractAddress, minPrice, maxPrice) {
  try {
    if (!wallets || wallets.length === 0) {
      return ctx.reply('❌ No minting wallets loaded.');
    }
    if (!ethers.isAddress(contractAddress)) {
      return ctx.reply('❌ Invalid contract address.');
    }

    const { label, openseaSlug } = getChainRpcPool(chainKey);
    const contractLower = contractAddress.toLowerCase();

    await ctx.reply(
      `🔎 Scanning offers on <b>${label}</b>\n` +
      `Contract: <code>${escapeHtml(contractAddress)}</code>\n` +
      `Wallets: <b>${wallets.length}</b>\n` +
      `Please wait...`,
      { parse_mode: 'HTML' }
    );

    let slug;
    try {
      slug = await resolveCollectionSlug(contractAddress, openseaSlug);
    } catch (err) {
      return ctx.reply(`❌ OpenSea collection lookup failed: ${err.message}`);
    }
    if (!slug) return ctx.reply('❌ No OpenSea collection found for that contract on this chain.');

    let ethUsd = null;
    try { ethUsd = await getEthPriceUsd(); } catch { /* optional */ }

    let ownedCount = 0;
    let offerChecked = 0;
    let offerFound = 0;
    let filteredOut = 0;
    const matches = [];
    const debugOwned = [];

    for (const w of wallets) {
      let tokenIds = [];

      // 1) OpenSea account NFTs
      try {
        let next = null;
        let pages = 0;
        do {
          const path =
            `/chain/${openseaSlug}/account/${w.address}/nfts?limit=50` +
            (next ? `&next=${encodeURIComponent(next)}` : '');
          const data = await openseaFetch(path);
          const nfts = data.nfts || [];
          for (const item of nfts) {
            const c = String(
              item.contract ||
              item.contract_address ||
              item.token_contract ||
              item.collection?.contract ||
              ''
            ).toLowerCase();
            if (c && c !== contractLower) continue;
            // if contract field missing, still try when collection slug matches
            const itemSlug = item.collection || item.collection_slug || '';
            if (!c && itemSlug && String(itemSlug).toLowerCase() !== String(slug).toLowerCase()) continue;
            if (!c && !itemSlug) continue;

            const id = item.identifier ?? item.token_id ?? item.tokenId;
            if (id != null) tokenIds.push(String(id));
          }
          next = data.next || null;
          pages += 1;
        } while (next && pages < 6);
      } catch (err) {
        debugOwned.push(`${w.address.slice(0, 10)}... NFT fetch err: ${(err.message || '').slice(0, 50)}`);
      }

      tokenIds = [...new Set(tokenIds)];
      ownedCount += tokenIds.length;
      if (tokenIds.length > 0) {
        debugOwned.push(`${w.address.slice(0, 10)}... owns ${tokenIds.length} token(s)`);
      }

      for (const tokenId of tokenIds.slice(0, 40)) {
        offerChecked += 1;
        let offer = null;

        // 2) best offer
        try {
          const best = await openseaFetch(
            `/offers/collection/${encodeURIComponent(slug)}/nfts/${encodeURIComponent(tokenId)}/best`
          );
          offer = best?.offer || best;
        } catch {
          // try full offers list
          try {
            const all = await openseaFetch(
              `/offers/collection/${encodeURIComponent(slug)}/nfts/${encodeURIComponent(tokenId)}?limit=5`
            );
            const list = all?.offers || [];
            offer = list[0] || null;
          } catch {
            offer = null;
          }
        }

        if (!offer || offer.status && String(offer.status).toUpperCase() === 'INACTIVE') {
          continue;
        }
        offerFound += 1;

        const parsed = offerPriceToNativeAndUsd(offer);
        if (!parsed) {
          filteredOut += 1;
          const rawPrice = JSON.stringify(offer.price || offer.current_price || {}).slice(0, 120);
          // string-only debug row (not acceptable)
          matches.push({
            line: `⚠️ ${w.address.slice(0, 10)}... #${tokenId} price parse failed: <code>${escapeHtml(rawPrice)}</code>`,
            wallet: null,
            tokenId: String(tokenId),
            orderHash: null,
          });
          continue;
        }

        let usd = parsed.usd;
        if (usd == null && ethUsd && ['ETH', 'WETH'].includes(parsed.currency)) {
          usd = parsed.native * ethUsd;
        }

        let pass = true;
        if (minPrice) {
          if (minPrice.kind === 'usd') {
            if (usd == null || usd < minPrice.value) pass = false;
          } else if (parsed.native < minPrice.value) pass = false;
        }
        if (pass && maxPrice) {
          if (maxPrice.kind === 'usd') {
            if (usd == null || usd > maxPrice.value) pass = false;
          } else if (parsed.native > maxPrice.value) pass = false;
        }

        if (!pass) {
          filteredOut += 1;
          continue;
        }

        const priceTxt =
          usd != null
            ? `${parsed.native.toFixed(5)} ${parsed.currency} (≈ $${usd.toFixed(2)})`
            : `${parsed.native.toFixed(5)} ${parsed.currency}`;

        const orderHash =
          offer.order_hash ||
          offer.orderHash ||
          offer.hash ||
          null;
        const protocolAddress =
          offer.protocol_address ||
          offer.protocolAddress ||
          '0x0000000000000068F116a894984e2DB1123eB395';

        matches.push({
          line: `✅ ${w.address.slice(0, 10)}... #${tokenId} → <b>${priceTxt}</b>`,
          wallet: w,
          tokenId: String(tokenId),
          orderHash,
          protocolAddress,
          priceTxt,
          slug,
        });
      }
    }

    const debug =
      `Slug: <code>${escapeHtml(slug)}</code>\n` +
      `Owned tokens found: <b>${ownedCount}</b>\n` +
      `Offers checked: <b>${offerChecked}</b>\n` +
      `Offers found: <b>${offerFound}</b>\n` +
      `Filtered by price: <b>${filteredOut}</b>\n` +
      (debugOwned.length ? `\n${debugOwned.slice(0, 12).join('\n')}` : '');

    if (matches.length === 0) {
      return ctx.reply(
        `ℹ️ No matching offers.\n\n${debug}\n\n` +
        `Tips:\n` +
        `• Confirm wallets own this collection on OpenSea\n` +
        `• Try min <code>$0</code> and max <code>none</code>`,
        { parse_mode: 'HTML' }
      );
    }

    const lines = matches.map((m) => m.line).slice(0, 40).join('\n');
    const header =
      `📋 <b>Offers</b> (${label})\n` +
      `Collection: <code>${escapeHtml(slug)}</code>\n` +
      `Matches: <b>${matches.length}</b>\n\n`;

    await ctx.reply(header + lines, { parse_mode: 'HTML' });
    await ctx.reply(`🧾 Debug\n${debug}`, { parse_mode: 'HTML' });

    const acceptable = matches.filter((m) => m.wallet && m.orderHash);
    if (acceptable.length === 0) {
      return ctx.reply('No offers can be accepted automatically (missing order hash).');
    }

    pendingAcceptOffers = {
      matches: acceptable,
      chainKey,
      contract: contractAddress,
      slug,
    };

    await ctx.reply(
      `💸 Accept <b>${acceptable.length}</b> offer(s)?\n\n` +
      `Type <code>yes</code> to accept, or <code>no</code> to cancel.`,
      { parse_mode: 'HTML' }
    );
  } catch (err) {
    await ctx.reply(`❌ Offers scan failed: ${err.message}`);
  }
}

async function runCollectNfts(ctx, contractAddress, toAddress, tokenIdList, chainKey = 'rh') {
  try {
    if (!wallets || wallets.length === 0) {
      return ctx.reply('❌ No minting wallets loaded.');
    }
    if (!ethers.isAddress(contractAddress)) {
      return ctx.reply('❌ Invalid NFT contract address.');
    }
    if (!ethers.isAddress(toAddress)) {
      return ctx.reply('❌ Invalid destination wallet address.');
    }

    const { pool, label, openseaSlug } = getChainRpcPool(chainKey);
    const provider = pool.current();
    const results = [];
    const wantAll = String(tokenIdList || '').trim().toLowerCase() === 'all';

    let tokenIds = [];
    if (!wantAll) {
      tokenIds = tokenIdList
        .split(',')
        .map((s) => s.trim())
        .filter(Boolean)
        .map((s) => {
          if (!/^\d+$/.test(s)) throw new Error(`Invalid token id: ${s}`);
          return BigInt(s);
        });

      if (tokenIds.length === 0) {
        return ctx.reply('❌ No token IDs provided. Example: 1,2,5  or  all');
      }
    }

    await ctx.reply(
      `📦 Collecting ${wantAll ? '<b>ALL</b> tokens' : `<b>${tokenIds.length}</b> token(s)`} on <b>${label}</b>\n` +
      `Contract: <code>${escapeHtml(contractAddress)}</code>\n` +
      `To: <code>${escapeHtml(toAddress)}</code>\n` +
      `From: <b>${wallets.length}</b> wallets...`,
      { parse_mode: 'HTML' }
    );

    let successCount = 0;
    const successWallets = new Set();

    for (const w of wallets) {
      const signer = w.signer.connect(provider);
      const nft = new ethers.Contract(contractAddress, ERC721_ABI, signer);

      let idsForWallet = tokenIds;
      if (wantAll) {
        idsForWallet = [];
        let listed = false;

        try {
          const balance = await nft.balanceOf(w.address);
          const count = Number(balance);
          if (count > 0) {
            for (let i = 0; i < count; i++) {
              const id = await nft.tokenOfOwnerByIndex(w.address, i);
              idsForWallet.push(id);
            }
          }
          listed = true;
        } catch {
          listed = false;
        }

        if (!listed) {
          try {
            const contractLower = contractAddress.toLowerCase();
            let next = null;
            let pages = 0;

            do {
              const path =
                `/chain/${openseaSlug}/account/${w.address}/nfts?limit=50` +
                (next ? `&next=${encodeURIComponent(next)}` : '');
              const data = await openseaFetch(path);
              const nfts = data.nfts || data.tokens || [];

              for (const item of nfts) {
                const itemContract = (
                  item.contract ||
                  item.contract_address ||
                  item.token_contract ||
                  ''
                ).toLowerCase();
                if (itemContract && itemContract !== contractLower) continue;

                const idRaw = item.identifier ?? item.token_id ?? item.tokenId ?? null;
                if (idRaw === null || idRaw === undefined) continue;
                idsForWallet.push(BigInt(String(idRaw)));
              }

              next = data.next || null;
              pages += 1;
            } while (next && pages < 10);
          } catch (err) {
            results.push(
              `❌ ${w.address.slice(0, 10)}... cannot list tokens → ${(err.message || 'failed').slice(0, 70)}`
            );
            continue;
          }
        }

        if (idsForWallet.length === 0) continue;
      }

      for (const tokenId of idsForWallet) {
        try {
          const owner = (await nft.ownerOf(tokenId)).toLowerCase();
          if (owner !== w.address.toLowerCase()) continue;

          const tx = await nft.safeTransferFrom(w.address, toAddress, tokenId);
          await tx.wait();
          successCount += 1;
          successWallets.add(w.address.toLowerCase());
          results.push(
            `✅ ${w.address.slice(0, 10)}... sent #${tokenId.toString()} | ${tx.hash.slice(0, 12)}...`
          );
        } catch (err) {
          results.push(
            `❌ ${w.address.slice(0, 10)}... #${tokenId.toString()} → ${(err.message || 'failed').slice(0, 70)}`
          );
        }
      }
    }

    if (results.length === 0) {
      return ctx.reply('ℹ️ Nothing to collect (no owned tokens found).');
    }

    await ctx.reply(
      `📦 <b>Collect NFTs result</b> (${label})\n` +
      `Sent <b>${successCount}</b> token(s) from <b>${successWallets.size}</b> wallet(s)\n\n` +
      results.join('\n'),
      { parse_mode: 'HTML' }
    );
  } catch (err) {
    await ctx.reply(`❌ Collect failed: ${err.message}`);
  }
}

// ===== BUTTON MENU =====
const mainMenu = Markup.keyboard([
  ['📊 Status', '👛 Wallets'],
  ['💰 RH Balances', '💎 ETH Balances'],
  ['💜 Ink Balances', '🟧 ARC Balances'],
  ['⏸ Pause RH', '▶️ Resume RH'],
  ['⏸ Pause ETH', '▶️ Resume ETH'],
  ['⏸ Pause Ink', '▶️ Resume Ink'],
  ['⏸ Pause ARC', '▶️ Resume ARC'],
  ['🎯 Sponsor ON', '🎯 Sponsor OFF'],
  ['⛽ Fund Gas', '📦 Collect NFTs'],
  ['💸 Offers'],
  ['⏸ Pause All', '▶️ Resume All'],
  ['ℹ️ Help']
]).resize();

bot.start(async (ctx) => {
  if (!isAuthorizedChat(ctx)) {
    return ctx.reply('Unauthorized.');
  }
  await ctx.reply('🤖 Mint Copy Bot\n\nChoose an option:', mainMenu);
});

bot.hears('📊 Status', async (ctx) => {
  if (!isAuthorizedChat(ctx)) return;

  const mintingWalletsCount = wallets?.length || (WALLET_ADDRESS ? 1 : 0);

  const globalState = isPaused ? '⏸ Paused' : '▶️ Running';
  const rhState = isRhPaused ? '⏸ Paused' : '▶️ Running';
  const ethState = isEthPaused ? '⏸ Paused' : '▶️ Running';

  const rhMode = chainConfigs.robinhood.dryRun ? '🧪 Dry Run' : '🔥 Live';
  const ethMode = chainConfigs.ethereum.dryRun ? '🧪 Dry Run' : '🔥 Live';

  let mintingList = 'None';
  if (wallets && wallets.length > 0) {
    mintingList = wallets
      .map((w, i) => `${i + 1}. <code>${escapeHtml(w.address.slice(0, 12))}...</code>`)
      .join('\n');
  } else if (WALLET_ADDRESS) {
    mintingList = `<code>${escapeHtml(WALLET_ADDRESS.slice(0, 12))}...</code>`;
  }

  const message =
    `📊 <b>Bot Status</b>\n\n` +
    `Global: <b>${globalState}</b>\n` +
    `Sponsor mode: <b>${isSponsorMode ? '🎯 ON' : 'OFF'}</b>\n` +
    `Poll: <b>${POLL_INTERVAL_MS}ms</b>\n` +
    `Watched wallets: <b>${watchedWallets.length}</b>\n` +
    `Minting wallets: <b>${mintingWalletsCount}</b>\n` +
    `${mintingList}\n\n` +
    `🟢 <b>Robinhood</b>\n` +
    `State: <b>${rhState}</b>\n` +
    `Mode: <b>${rhMode}</b>\n` +
    `Enabled: <b>${chainConfigs.robinhood.enabled ? 'ON' : 'OFF'}</b>\n` +
    `Max price: <b>${chainConfigs.robinhood.maxPriceEth ?? 'not set'}</b>\n\n` +
    `🟦 <b>Ethereum</b>\n` +
    `State: <b>${ethState}</b>\n` +
    `Mode: <b>${ethMode}</b>\n` +
    `Enabled: <b>${chainConfigs.ethereum.enabled ? 'ON' : 'OFF'}</b>\n` +
    `Max price: <b>${chainConfigs.ethereum.maxPriceEth ?? 'not set'}</b>\n\n` +
    `💜 <b>Ink</b>\n` +
    `State: <b>${isInkPaused ? '⏸ Paused' : '▶️ Running'}</b>\n` +
    `Mode: <b>${chainConfigs.ink.dryRun ? '🧪 Dry Run' : '🔥 Live'}</b>\n` +
    `Enabled: <b>${chainConfigs.ink.enabled ? 'ON' : 'OFF'}</b>\n` +
    `Max price: <b>${chainConfigs.ink.maxPriceEth ?? 'not set'}</b>\n\n` +
    `🟧 <b>Arc</b>\n` +
    `State: <b>${isArcPaused ? '⏸ Paused' : '▶️ Running'}</b>\n` +
    `Mode: <b>${chainConfigs.arc.dryRun ? '🧪 Dry Run' : '🔥 Live'}</b>\n` +
    `Enabled: <b>${chainConfigs.arc.enabled ? 'ON' : 'OFF'}</b>\n` +
    `Max price: <b>${chainConfigs.arc.maxPriceEth ?? 'not set'}</b>\n\n` +
    `🔢 Quantities: <b>${process.env.QUANTITY_TRIES || '10,5,3,2,1'}</b>`;

  await ctx.reply(message, { parse_mode: 'HTML' });
});

bot.hears('👛 Wallets', async (ctx) => {
  if (!isAuthorizedChat(ctx)) return;
  await refreshWatchedWallets();
  if (watchedWallets.length === 0) {
    return ctx.reply('No watched wallets yet.\nUse /addwallet 0x...');
  }
  const list = watchedWallets.map((w, i) => `${i + 1}. ${w}`).join('\n');
  await ctx.reply(`Watching ${watchedWallets.length} wallet(s):\n${list}`);
});

bot.hears('⚙️ Settings', async (ctx) => {
  if (!isAuthorizedChat(ctx)) return;
  await ctx.reply(
    `Settings\n\nDRY_RUN: ${DRY_RUN}\nMAX_PRICE_ETH: ${MAX_PRICE_ETH ?? 'not set'}\nQUANTITY_TRIES: ${process.env.QUANTITY_TRIES || '10,5,3,2,1'}`
  );
});

bot.hears('ℹ️ Help', async (ctx) => {
  if (!isAuthorizedChat(ctx)) return;
  await ctx.reply(
    `Commands:\n/start — show menu\n/addwallet 0x...\n/removewallet 0x...\n/wallets\n/status\n/help`
  );
});

bot.hears('⏸ Pause', async (ctx) => {
  if (!isAuthorizedChat(ctx)) return;
  isPaused = true;
  await ctx.reply('⏸ Bot paused.\nIt will still detect mints but will not try to mint.');
});

bot.hears('▶️ Resume', async (ctx) => {
  if (!isAuthorizedChat(ctx)) return;
  isPaused = false;
  await ctx.reply('▶️ Bot resumed.\nMinting is active again.');
});

bot.hears('💰 Balances', async (ctx) => {
  if (!isAuthorizedChat(ctx)) return;

  try {
    const provider = rpcPool.current();
    const list = wallets.length > 0 ? wallets : [{ address: WALLET_ADDRESS }];

    if (!list[0]?.address) {
      return ctx.reply('No minting wallets configured.');
    }

    let message = `💰 <b>Minting wallet balances</b>\n\n`;

    for (const w of list) {
      const balance = await provider.getBalance(w.address);
      const eth = Number(ethers.formatEther(balance)).toFixed(5);
      message += `<code>${escapeHtml(w.address.slice(0, 10))}...</code> → <b>${eth} ETH</b>\n`;
    }

    await ctx.reply(message, { parse_mode: 'HTML' });
  } catch (err) {
    await ctx.reply(`❌ Failed to fetch balances: ${err.message}`);
  }
});

bot.hears('⏸ Pause RH', async (ctx) => {
  if (!isAuthorizedChat(ctx)) return;
  isRhPaused = true;
  await ctx.reply('⏸ Robinhood paused');
});

bot.hears('▶️ Resume RH', async (ctx) => {
  if (!isAuthorizedChat(ctx)) return;
  isRhPaused = false;
  await ctx.reply('▶️ Robinhood resumed');
});

bot.hears('⏸ Pause ETH', async (ctx) => {
  if (!isAuthorizedChat(ctx)) return;
  isEthPaused = true;
  await ctx.reply('⏸ Ethereum paused');
});

bot.hears('▶️ Resume ETH', async (ctx) => {
  if (!isAuthorizedChat(ctx)) return;
  isEthPaused = false;
  await ctx.reply('▶️ Ethereum resumed');
});

bot.hears('⏸ Pause Ink', async (ctx) => {
  if (!isAuthorizedChat(ctx)) return;
  isInkPaused = true;
  await ctx.reply('⏸ Ink paused');
});

bot.hears('▶️ Resume Ink', async (ctx) => {
  if (!isAuthorizedChat(ctx)) return;
  isInkPaused = false;
  await ctx.reply('▶️ Ink resumed');
});

bot.hears('⏸ Pause ARC', async (ctx) => {
  if (!isAuthorizedChat(ctx)) return;
  isArcPaused = true;
  await ctx.reply('⏸ Arc paused');
});

bot.hears('▶️ Resume ARC', async (ctx) => {
  if (!isAuthorizedChat(ctx)) return;
  isArcPaused = false;
  await ctx.reply('▶️ Arc resumed');
});

bot.hears('⏸ Pause All', async (ctx) => {
  if (!isAuthorizedChat(ctx)) return;
  isPaused = true;
  isRhPaused = true;
  isEthPaused = true;
  isInkPaused = true;
  isArcPaused = true;
  await ctx.reply('⏸ All minting paused');
});

bot.hears('▶️ Resume All', async (ctx) => {
  if (!isAuthorizedChat(ctx)) return;
  isPaused = false;
  isRhPaused = false;
  isEthPaused = false;
  isInkPaused = false;
  isArcPaused = false;
  await ctx.reply('▶️ All minting resumed');
});

bot.hears('🎯 Sponsor ON', async (ctx) => {
  if (!isAuthorizedChat(ctx)) return;
  if (!sponsorWallet) {
    return ctx.reply('❌ No sponsor wallet configured in .env');
  }
  isSponsorMode = true;
  await ctx.reply(
    '🎯 <b>Sponsor mode ON</b>\nSponsor pays gas + mint price.\nNFTs will go to your normal wallets.',
    { parse_mode: 'HTML' }
  );
});

bot.hears('🎯 Sponsor OFF', async (ctx) => {
  if (!isAuthorizedChat(ctx)) return;
  isSponsorMode = false;
  await ctx.reply('🎯 Sponsor mode OFF\nEach wallet pays its own gas + mint price again.');
});

bot.hears('⛽ Fund Gas', async (ctx) => {
  if (!isAuthorizedChat(ctx)) return;

  if (!sponsorWallet) {
    return ctx.reply('❌ No sponsor/funder wallet configured.');
  }

  pendingFundGas = { step: 'chain' };
  pendingCollect = null;

  await ctx.reply(
    '⛽ <b>Fund Gas</b>\n\n' +
    'Step 1/2 — Choose chain:\n' +
    '<code>rh</code> / <code>eth</code> / <code>ink</code> / <code>arc</code>\n\n' +
    'Or type <code>cancel</code>.',
    { parse_mode: 'HTML' }
  );
});

bot.hears('💸 Offers', async (ctx) => {
  if (!isAuthorizedChat(ctx)) return;
  pendingOffers = { step: 'chain' };
  pendingFundGas = null;
  pendingCollect = null;
  await ctx.reply(
    '💸 <b>List Offers</b>\n\n' +
    'Step 1/4 — Chain:\n' +
    '<code>rh</code> / <code>eth</code> / <code>ink</code> / <code>arc</code>\n\n' +
    'Or <code>cancel</code>.',
    { parse_mode: 'HTML' }
  );
});

bot.hears('📦 Collect NFTs', async (ctx) => {
  if (!isAuthorizedChat(ctx)) return;

  pendingCollect = { step: 'chain' };
  pendingFundGas = null;

  await ctx.reply(
    '📦 <b>Collect NFTs</b>\n\n' +
    'Step 1/4 — Choose chain:\n' +
    '<code>rh</code> / <code>eth</code> / <code>ink</code> / <code>arc</code>\n\n' +
    'Or type <code>cancel</code>.',
    { parse_mode: 'HTML' }
  );
});

bot.hears('💰 RH Balances', async (ctx) => {
  if (!isAuthorizedChat(ctx)) return;
  try {
    const provider = rpcPool.current();
    const list = wallets.length > 0 ? wallets : [{ address: WALLET_ADDRESS }];
    let message = `💰 <b>Robinhood balances</b>\n\n`;
    for (const w of list) {
      const balance = await provider.getBalance(w.address);
      const eth = Number(ethers.formatEther(balance)).toFixed(5);
      message += `<code>${escapeHtml(w.address.slice(0, 10))}...</code> → <b>${eth}</b>\n`;
    }
    await ctx.reply(message, { parse_mode: 'HTML' });
  } catch (err) {
    await ctx.reply(`❌ RH balances failed: ${err.message}`);
  }
});

bot.hears('💎 ETH Balances', async (ctx) => {
  if (!isAuthorizedChat(ctx)) return;
  try {
    if (!ethRpcPool) return ctx.reply('Ethereum RPC not ready');
    const provider = ethRpcPool.current();
    const list = wallets.length > 0 ? wallets : [{ address: WALLET_ADDRESS }];
    let message = `💎 <b>Ethereum balances</b>\n\n`;
    for (const w of list) {
      const balance = await provider.getBalance(w.address);
      const eth = Number(ethers.formatEther(balance)).toFixed(5);
      message += `<code>${escapeHtml(w.address.slice(0, 10))}...</code> → <b>${eth} ETH</b>\n`;
    }
    await ctx.reply(message, { parse_mode: 'HTML' });
  } catch (err) {
    await ctx.reply(`❌ ETH balances failed: ${err.message}`);
  }
});

bot.hears('💜 Ink Balances', async (ctx) => {
  if (!isAuthorizedChat(ctx)) return;
  try {
    if (!inkRpcPool) {
      return ctx.reply('Ink RPC not ready (is INK_ENABLED=true and RPCs set?)');
    }
    const provider = inkRpcPool.current();
    const list = wallets.length > 0 ? wallets : [{ address: WALLET_ADDRESS }];
    let message = `💜 <b>Ink balances</b>\n\n`;
    for (const w of list) {
      const balance = await provider.getBalance(w.address);
      const eth = Number(ethers.formatEther(balance)).toFixed(5);
      message += `<code>${escapeHtml(w.address.slice(0, 10))}...</code> → <b>${eth}</b>\n`;
    }
    await ctx.reply(message, { parse_mode: 'HTML' });
  } catch (err) {
    await ctx.reply(`❌ Ink balances failed: ${err.message}`);
  }
});

bot.hears('🟧 ARC Balances', async (ctx) => {
  if (!isAuthorizedChat(ctx)) return;
  try {
    if (!arcRpcPool) {
      return ctx.reply('Arc RPC not ready (is ARC_ENABLED=true and RPCs set?)');
    }
    const provider = arcRpcPool.current();
    const list = wallets.length > 0 ? wallets : [{ address: WALLET_ADDRESS }];
    let message = `🟧 <b>Arc balances</b> (native USDC)\n\n`;
    for (const w of list) {
      const balance = await provider.getBalance(w.address);
      const amount = Number(ethers.formatEther(balance)).toFixed(5);
      message += `<code>${escapeHtml(w.address.slice(0, 10))}...</code> → <b>${amount} USDC</b>\n`;
    }
    await ctx.reply(message, { parse_mode: 'HTML' });
  } catch (err) {
    await ctx.reply(`❌ Arc balances failed: ${err.message}`);
  }
});

bot.on('text', async (ctx, next) => {
  if (!isAuthorizedChat(ctx)) return next();

  const text = (ctx.message.text || '').trim();

  // Let commands and menu buttons be handled by their own handlers
  if (
    text.startsWith('/') ||
    text.startsWith('⛽') ||
    text.startsWith('📦') ||
    text.startsWith('📊') ||
    text.startsWith('🎯') ||
    text.startsWith('⏸') ||
    text.startsWith('▶️') ||
    text.startsWith('💰') ||
    text.startsWith('💎') ||
    text.startsWith('💜') ||
    text.startsWith('🟧') ||
    text.startsWith('👛') ||
    text.startsWith('ℹ️') ||
    text.startsWith('💸')
  ) {
    return next();
  }

  
  // If no interactive flow is active, do not block other handlers
  if (!pendingFundGas && !pendingCollect && !pendingOffers && !pendingAcceptOffers) {
    return next();
  }

  if (text.toLowerCase() === 'cancel') {
    pendingFundGas = null;
    pendingCollect = null;
    pendingOffers = null;
    pendingAcceptOffers = null;
    return ctx.reply('Cancelled.');
  }

  // Accept offers confirmation
  if (pendingAcceptOffers) {
    const ans = text.toLowerCase();
    if (ans === 'no' || ans === 'n') {
      pendingAcceptOffers = null;
      return ctx.reply('Cancelled offer accept.');
    }
    if (ans === 'yes' || ans === 'y') {
      const payload = pendingAcceptOffers;
      pendingAcceptOffers = null;
      await runAcceptOffers(ctx, payload);
      return;
    }
    return ctx.reply('Type <code>yes</code> to accept or <code>no</code> to cancel.', {
      parse_mode: 'HTML',
    });
  }

  // Fund gas flow: chain → amount
  if (pendingFundGas && typeof pendingFundGas === 'object') {
    if (pendingFundGas.step === 'chain') {
      const chainKey = parseChainKey(text);
      if (!chainKey) {
        return ctx.reply('❌ Invalid chain. Use: rh / eth / ink');
      }
      pendingFundGas = { step: 'amount', chain: chainKey };
      const tokenName = chainKey === 'arc' ? 'USDC' : 'ETH';
      return ctx.reply(
        `⛽ Step 2/2 — Amount for <b>each</b> wallet on <b>${chainKey}</b>.\n\n` +
        `Native ${tokenName}: <code>0.002</code>\n` +
        `Or dollars: <code>$3</code> / <code>3usd</code>`,
        { parse_mode: 'HTML' }
      );
    }

    if (pendingFundGas.step === 'amount') {
      const chainKey = pendingFundGas.chain || 'rh';
      pendingFundGas = null;
      await runFundGas(ctx, text, chainKey);
      return;
    }
  }

    // Offers flow: chain → contract → min → max
  if (pendingOffers) {
    if (pendingOffers.step === 'chain') {
      const chainKey = parseChainKey(text);
      if (!chainKey) return ctx.reply('❌ Invalid chain. Use: rh / eth / ink / arc');
      pendingOffers = { step: 'contract', chain: chainKey };
      return ctx.reply('💸 Step 2/4 — Send the collection <b>contract address</b>.', { parse_mode: 'HTML' });
    }

    if (pendingOffers.step === 'contract') {
      if (!ethers.isAddress(text)) return ctx.reply('❌ Invalid contract address.');
      pendingOffers = { step: 'min', chain: pendingOffers.chain, contract: text };
      return ctx.reply(
        '💸 Step 3/4 — Min price.\nExamples: <code>$20</code> or <code>0.01</code>',
        { parse_mode: 'HTML' }
      );
    }

    if (pendingOffers.step === 'min') {
      try {
        const minPrice = parsePriceInput(text);
        if (!minPrice) return ctx.reply('❌ Min price required.');
        pendingOffers = {
          step: 'max',
          chain: pendingOffers.chain,
          contract: pendingOffers.contract,
          min: minPrice,
        };
        return ctx.reply(
          '💸 Step 4/4 — Max price.\nExamples: <code>$100</code> / <code>0.05</code> / <code>none</code>',
          { parse_mode: 'HTML' }
        );
      } catch {
        return ctx.reply('❌ Invalid min price.');
      }
    }

    if (pendingOffers.step === 'max') {
      try {
        const maxPrice = parsePriceInput(text);
        const { chain, contract, min } = pendingOffers;
        pendingOffers = null;
        await runListOffers(ctx, chain, contract, min, maxPrice);
        return;
      } catch {
        return ctx.reply('❌ Invalid max price. Use a number, $amount, or none.');
      }
    }
  }

  // Collect flow: chain → contract → destination → ids
  if (pendingCollect) {
    if (pendingCollect.step === 'chain') {
      const chainKey = parseChainKey(text);
      if (!chainKey) {
        return ctx.reply('❌ Invalid chain. Use: rh / eth / ink');
      }
      pendingCollect = { step: 'contract', chain: chainKey };
      return ctx.reply(
        '📦 Step 2/4 — Send the NFT <b>contract address</b>.',
        { parse_mode: 'HTML' }
      );
    }

    if (pendingCollect.step === 'contract') {
      if (!ethers.isAddress(text)) {
        return ctx.reply('❌ Invalid contract address. Try again, or type cancel.');
      }
      pendingCollect = {
        step: 'destination',
        chain: pendingCollect.chain,
        contract: text,
      };
      return ctx.reply(
        '📦 Step 3/4 — Send the <b>destination wallet address</b>.',
        { parse_mode: 'HTML' }
      );
    }

    if (pendingCollect.step === 'destination') {
      if (!ethers.isAddress(text)) {
        return ctx.reply('❌ Invalid destination address. Try again, or type cancel.');
      }
      pendingCollect = {
        step: 'ids',
        chain: pendingCollect.chain,
        contract: pendingCollect.contract,
        to: text,
      };
      return ctx.reply(
        '📦 Step 4/4 — Token IDs:\n<code>1,2,5</code> or <code>all</code>',
        { parse_mode: 'HTML' }
      );
    }

    if (pendingCollect.step === 'ids') {
      const chainKey = pendingCollect.chain || 'rh';
      const contract = pendingCollect.contract;
      const to = pendingCollect.to;
      pendingCollect = null;
      await runCollectNfts(ctx, contract, to, text, chainKey);
      return;
    }
  }

  return next();
});

bot.command('addwallet', async (ctx) => {
  if (!isAuthorizedChat(ctx)) return;
  const address = (ctx.message.text.split(' ')[1] || '').trim();
  if (!ethers.isAddress(address)) {
    return ctx.reply('Usage: /addwallet 0xYourAddressHere — that doesn\'t look like a valid address.');
  }
  try {
    const result = await dbAddWallet(address);
    await refreshWatchedWallets();
    if (result.added) {
      ctx.reply(`✅ Now watching <code>${escapeHtml(address)}</code>. Total watched: ${watchedWallets.length}.`, { parse_mode: 'HTML' });
    } else {
      ctx.reply(`Already watching <code>${escapeHtml(address)}</code>.`, { parse_mode: 'HTML' });
    }
  } catch (err) {
    ctx.reply(`❌ Failed to add wallet: ${err.message}`);
  }
});

bot.command('removewallet', async (ctx) => {
  if (!isAuthorizedChat(ctx)) return;
  const address = (ctx.message.text.split(' ')[1] || '').trim();
  if (!ethers.isAddress(address)) {
    return ctx.reply('Usage: /removewallet 0xYourAddressHere');
  }
  try {
    const removed = await dbRemoveWallet(address);
    await refreshWatchedWallets();
    ctx.reply(
      removed
        ? `🗑 Stopped watching <code>${escapeHtml(address)}</code>. Total watched: ${watchedWallets.length}.`
        : `<code>${escapeHtml(address)}</code> wasn't in the watch list.`,
      { parse_mode: 'HTML' }
    );
  } catch (err) {
    ctx.reply(`❌ Failed to remove wallet: ${err.message}`);
  }
});

bot.command('wallets', async (ctx) => {
  if (!isAuthorizedChat(ctx)) return;
  await refreshWatchedWallets();
  if (watchedWallets.length === 0) {
    return ctx.reply('Not watching any wallets yet. Add one with /addwallet 0x...');
  }
  const list = watchedWallets.map((w, i) => `${i + 1}. <code>${escapeHtml(w)}</code>`).join('\n');
  ctx.reply(`Watching ${watchedWallets.length} wallet(s):\n${list}`, { parse_mode: 'HTML' });
});

bot.command('status', async (ctx) => {
  if (!isAuthorizedChat(ctx)) return;

  const mintingWalletsCount = wallets?.length || (WALLET_ADDRESS ? 1 : 0);

  const globalState = isPaused ? '⏸ Paused' : '▶️ Running';
  const rhState = isRhPaused ? '⏸ Paused' : '▶️ Running';
  const ethState = isEthPaused ? '⏸ Paused' : '▶️ Running';

  const rhMode = chainConfigs.robinhood.dryRun ? '🧪 Dry Run' : '🔥 Live';
  const ethMode = chainConfigs.ethereum.dryRun ? '🧪 Dry Run' : '🔥 Live';

  let mintingList = 'None';
  if (wallets && wallets.length > 0) {
    mintingList = wallets
      .map((w, i) => `${i + 1}. <code>${escapeHtml(w.address.slice(0, 12))}...</code>`)
      .join('\n');
  } else if (WALLET_ADDRESS) {
    mintingList = `<code>${escapeHtml(WALLET_ADDRESS.slice(0, 12))}...</code>`;
  }

  const message =
    `📊 <b>Bot Status</b>\n\n` +
    `Global: <b>${globalState}</b>\n` +
    `Sponsor mode: <b>${isSponsorMode ? '🎯 ON' : 'OFF'}</b>\n` +
    `Poll: <b>${POLL_INTERVAL_MS}ms</b>\n` +
    `Watched wallets: <b>${watchedWallets.length}</b>\n` +
    `Minting wallets: <b>${mintingWalletsCount}</b>\n` +
    `${mintingList}\n\n` +
    `🟢 <b>Robinhood</b>\n` +
    `State: <b>${rhState}</b>\n` +
    `Mode: <b>${rhMode}</b>\n` +
    `Enabled: <b>${chainConfigs.robinhood.enabled ? 'ON' : 'OFF'}</b>\n` +
    `Max price: <b>${chainConfigs.robinhood.maxPriceEth ?? 'not set'}</b>\n\n` +
    `🟦 <b>Ethereum</b>\n` +
    `State: <b>${ethState}</b>\n` +
    `Mode: <b>${ethMode}</b>\n` +
    `Enabled: <b>${chainConfigs.ethereum.enabled ? 'ON' : 'OFF'}</b>\n` +
    `Max price: <b>${chainConfigs.ethereum.maxPriceEth ?? 'not set'}</b>\n\n` +
    `💜 <b>Ink</b>\n` +
    `State: <b>${isInkPaused ? '⏸ Paused' : '▶️ Running'}</b>\n` +
    `Mode: <b>${chainConfigs.ink.dryRun ? '🧪 Dry Run' : '🔥 Live'}</b>\n` +
    `Enabled: <b>${chainConfigs.ink.enabled ? 'ON' : 'OFF'}</b>\n` +
    `Max price: <b>${chainConfigs.ink.maxPriceEth ?? 'not set'}</b>\n\n` +
    `🟧 <b>Arc</b>\n` +
    `State: <b>${isArcPaused ? '⏸ Paused' : '▶️ Running'}</b>\n` +
    `Mode: <b>${chainConfigs.arc.dryRun ? '🧪 Dry Run' : '🔥 Live'}</b>\n` +
    `Enabled: <b>${chainConfigs.arc.enabled ? 'ON' : 'OFF'}</b>\n` +
    `Max price: <b>${chainConfigs.arc.maxPriceEth ?? 'not set'}</b>\n\n` +
    `🔢 Quantities: <b>${process.env.QUANTITY_TRIES || '10,5,3,2,1'}</b>`;

  await ctx.reply(message, { parse_mode: 'HTML' });
});

bot.command('fundgas', async (ctx) => {
  if (!isAuthorizedChat(ctx)) return;

  if (!sponsorWallet) {
    return ctx.reply('❌ No sponsor/funder wallet configured.');
  }

  const parts = (ctx.message.text || '').trim().split(/\s+/);
  // /fundgas 0.002 rh
  const amountStr = parts[1];
  const chainKey = parseChainKey(parts[2] || 'rh') || 'rh';

  if (!amountStr) {
    pendingFundGas = { step: 'chain' };
    return ctx.reply(
      'Usage:\n' +
      '<code>/fundgas 0.002 rh</code>\n' +
      '<code>/fundgas $3 eth</code>\n' +
      '<code>/fundgas 5usd arc</code>\n\n' +
      'Chains: <code>rh</code> / <code>eth</code> / <code>ink</code> / <code>arc</code>\n' +
      'On Arc, $ amounts are treated as USDC (~$1 each)',
      { parse_mode: 'HTML' }
    );
  }

  await runFundGas(ctx, amountStr, chainKey);
});

bot.command('collect', async (ctx) => {
  if (!isAuthorizedChat(ctx)) return;

  const parts = (ctx.message.text || '').trim().split(/\s+/);
  // /collect 0xContract 0xDestination 1,2,5 rh
  const contract = parts[1];
  const toAddress = parts[2];
  const ids = parts[3];
  const chainKey = parseChainKey(parts[4] || 'rh') || 'rh';

  if (!contract || !toAddress || !ids) {
    pendingCollect = { step: 'chain' };
    pendingFundGas = null;
    return ctx.reply(
      'Usage:\n' +
      '<code>/collect 0xContract 0xDestination 1,2,5 rh</code>\n' +
      '<code>/collect 0xContract 0xDestination all eth</code>\n\n' +
      'Chains: <code>rh</code> / <code>eth</code> / <code>ink</code>',
      { parse_mode: 'HTML' }
    );
  }

  await runCollectNfts(ctx, contract, toAddress, ids, chainKey);
});

// ---------------------------------------------------------------------------
// Multi-RPC pool with failover
// ---------------------------------------------------------------------------

class RpcPool {
  constructor(urls, chainId) {
    this.providers = urls.map((url) => {
      const fetchRequest = new ethers.FetchRequest(url);
      fetchRequest.timeout = 10000; // ms — fail instead of hanging on a dead RPC
      return new ethers.JsonRpcProvider(fetchRequest, chainId, { staticNetwork: true });
    });
    this.index = 0;
  }
  current() {
    return this.providers[this.index];
  }
  rotate() {
    this.index = (this.index + 1) % this.providers.length;
    return this.current();
  }
  async withFailover(fn) {
    let lastErr;
    for (let i = 0; i < this.providers.length; i++) {
      try {
        return await fn(this.current());
      } catch (err) {
        lastErr = err;
        console.warn(`[rpc] provider #${this.index} failed (${err.message}). Rotating...`);
        this.rotate();
      }
    }
    throw lastErr;
  }
}

const rpcPool = new RpcPool(RPC_URLS, CHAIN_ID);

// ========== Multi-wallet support ==========
const PRIVATE_KEYS_RAW = (process.env.PRIVATE_KEYS || process.env.PRIVATE_KEY || '')
  .split(',')
  .map(k => k.trim())
  .filter(Boolean);

const WALLET_ADDRESSES_RAW = (process.env.WALLET_ADDRESSES || process.env.WALLET_ADDRESS || '')
  .split(',')
  .map(a => a.trim().toLowerCase())
  .filter(Boolean);

const wallets = [];

if (!DRY_RUN) {
  if (PRIVATE_KEYS_RAW.length === 0) {
    throw new Error('PRIVATE_KEYS or PRIVATE_KEY is required when DRY_RUN=false');
  }

  for (let i = 0; i < PRIVATE_KEYS_RAW.length; i++) {
    let key = PRIVATE_KEYS_RAW[i];
    if (!key.startsWith('0x')) key = '0x' + key;

    if (!/^0x[0-9a-fA-F]{64}$/.test(key)) {
      throw new Error(`Invalid private key at position ${i + 1}`);
    }

    const wallet = new ethers.Wallet(key);
    const expected = WALLET_ADDRESSES_RAW[i];

    if (expected && wallet.address.toLowerCase() !== expected) {
      throw new Error(`Private key #${i + 1} does not match WALLET_ADDRESSES #${i + 1}`);
    }

    wallets.push({
      address: wallet.address.toLowerCase(),
      signer: wallet
    });
  }

  console.log(`[startup] Loaded ${wallets.length} minting wallet(s)`);
}

// ===== Sponsor wallet (Option A) =====
let sponsorWallet = null;
// Always start with Sponsor OFF on every restart / deploy
let isSponsorMode = false;

const SPONSOR_PRIVATE_KEY_RAW = (process.env.SPONSOR_PRIVATE_KEY || '').trim();
const SPONSOR_ADDRESS = (process.env.SPONSOR_ADDRESS || '').toLowerCase();

if (SPONSOR_PRIVATE_KEY_RAW) {
  let key = SPONSOR_PRIVATE_KEY_RAW.startsWith('0x')
    ? SPONSOR_PRIVATE_KEY_RAW
    : `0x${SPONSOR_PRIVATE_KEY_RAW}`;

  if (!/^0x[0-9a-fA-F]{64}$/.test(key)) {
    throw new Error('SPONSOR_PRIVATE_KEY is not a valid 32-byte hex key');
  }

  const wallet = new ethers.Wallet(key);

  if (SPONSOR_ADDRESS && wallet.address.toLowerCase() !== SPONSOR_ADDRESS) {
    throw new Error('SPONSOR_PRIVATE_KEY does not match SPONSOR_ADDRESS');
  }

  sponsorWallet = {
    address: wallet.address.toLowerCase(),
    signer: wallet
  };

  console.log(`[startup] Sponsor wallet loaded: ${sponsorWallet.address.slice(0, 10)}...`);
} else {
  console.log('[startup] No sponsor wallet configured');
}
// ===== End Sponsor wallet =====

// Keep old single signer for compatibility with other parts of the code
const signer = wallets.length > 0 ? wallets[0].signer.connect(rpcPool.current()) : null;
const WALLET_ADDRESS_EFFECTIVE = wallets.length > 0 ? wallets[0].address : WALLET_ADDRESS;

// ===== Ethereum RPC pool (Stage 2) =====
const ethRpcPool = chainConfigs.ethereum.enabled && chainConfigs.ethereum.rpcUrls.length > 0
  ? new RpcPool(chainConfigs.ethereum.rpcUrls, chainConfigs.ethereum.chainId)
  : null;

let ethLastCheckedBlock = null;
const ethSeenTxHashes = new Set();
// ===== End Ethereum RPC pool =====

// ===== Ink RPC pool =====
const inkRpcPool = chainConfigs.ink.enabled && chainConfigs.ink.rpcUrls.length > 0
  ? new RpcPool(chainConfigs.ink.rpcUrls, chainConfigs.ink.chainId)
  : null;

let inkLastCheckedBlock = null;
const inkSeenTxHashes = new Set();
// ===== End Ink RPC pool =====

// ===== Arc RPC pool =====
const arcRpcPool = chainConfigs.arc.enabled && chainConfigs.arc.rpcUrls.length > 0
  ? new RpcPool(chainConfigs.arc.rpcUrls, chainConfigs.arc.chainId)
  : null;

let arcLastCheckedBlock = null;
const arcSeenTxHashes = new Set();
// ===== End Arc RPC pool =====

// ---------------------------------------------------------------------------
// OpenSea helpers
// ---------------------------------------------------------------------------

async function openseaFetch(path_, { method, body } = {}) {
  const res = await fetchWithTimeout(OPENSEA_BASE + path_, {
    method: method || 'GET',
    headers: {
      accept: 'application/json',
      'x-api-key': OPENSEA_API_KEY,
      ...(body ? { 'content-type': 'application/json' } : {}),
    },
    body: body ? JSON.stringify(body) : undefined,
  }, 10000);
  if (!res.ok) {
    const text = await res.text().catch(() => '');
    throw new Error(`${res.status} ${res.statusText} on ${path_}: ${text.slice(0, 300)}`);
  }
  return res.json();
}

async function resolveCollectionSlug(contractAddress, openseaSlug = OPENSEA_CHAIN_SLUG) {
  const data = await openseaFetch(`/chain/${openseaSlug}/contract/${contractAddress}`);
  return data.collection || null;
}

function readMintTxFields(raw) {
  const to = raw.to || raw.target || raw.contract_address || null;
  const data = raw.data || raw.calldata || raw.call_data || null;
  const value = raw.value ?? raw.price ?? '0';
  return { to, data, value: String(value) };
}

async function buildDropMintTransaction(slug, minter, quantity) {
  return openseaFetch(`/drops/${slug}/mint`, { method: 'POST', body: { minter, quantity } });
}

// ---------------------------------------------------------------------------
// Fallback: direct on-chain mint when there's no OpenSea Drop
// ---------------------------------------------------------------------------

async function fetchAbiFromExplorer(contractAddress, explorerBase, explorerKey = '') {
  if (!explorerBase) {
    console.warn('[explorer] No explorer API base configured');
    return null;
  }

  // Note: This path works for Blockscout-style explorers (Robinhood + Ink).
  // Etherscan uses a different format, so Ethereum fallback may still fail for now.
  const url = `${explorerBase}/smart-contracts/${contractAddress}${
    explorerKey ? `?apikey=${explorerKey}` : ''
  }`;

  try {
    const res = await fetchWithTimeout(url, {}, 10000);
    if (!res.ok) return null;
    const data = await res.json();
    return data.abi || null;
  } catch (err) {
    console.warn(`[explorer] ABI fetch failed for ${contractAddress}: ${err.message}`);
    return null;
  }
}

function abiHasFunction(abi, name) {
  return Array.isArray(abi) && abi.some((f) => f.type === 'function' && f.name === name);
}

async function attemptDirectMint(contractAddress, sourceWallet, chainName = 'robinhood') {
  const chain = chainConfigs[chainName] || chainConfigs.robinhood;

  const activeRpcPool =
    chainName === 'ethereum' ? ethRpcPool :
    chainName === 'ink' ? inkRpcPool :
    chainName === 'arc' ? arcRpcPool :
    rpcPool;

  const activeDryRun = chain.dryRun;
  const explorerBase = chain.explorerApiBase;
  const explorerKey  = chain.explorerApiKey || '';
if (activeDryRun) {
    await notify(
      `⚙️ <b>Direct mint fallback</b>\n` +
      `Contract: <code>${escapeHtml(contractAddress)}</code>\n` +
      `🧪 Dry run only (not broadcast)`
    );
    return;
  }

  if (!signer && wallets.length === 0) {
    await notify(`❌ No minting wallet available for direct mint`);
    return;
  }

  if (!activeRpcPool) {
  await notify(`❌ No RPC pool ready for ${chainName}`);
  return;
  }
  const provider = activeRpcPool.current();
  const mintWallets = wallets.length > 0
    ? wallets
    : [{ address: WALLET_ADDRESS, signer: signer }];

  const EXTRA_MINT_ABIS = [
    'function mint() public payable',
    'function mint(uint256 quantity) public payable',
    'function mint(address to) public payable',
    'function mint(address to, uint256 quantity) public payable',
    'function publicMint() public payable',
    'function publicMint(uint256 quantity) public payable',
    'function claim() public payable',
    'function claim(uint256 quantity) public payable',
    'function claim(address to, uint256 quantity) public payable',
    'function safeMint(address to) public payable',
    'function safeMint(address to, uint256 quantity) public payable',
    'function mintNFT(uint256 quantity) public payable',
    'function mintPublic(uint256 quantity) public payable',
  ];

  const remoteAbi = await fetchAbiFromExplorer(contractAddress, explorerBase, explorerKey);
  const quantitiesToTry = [1, 2, 3, 5];
  const results = [];
  let anySuccess = false;

  for (const wallet of mintWallets) {
    const connectedSigner = wallet.signer.connect(provider);
    const candidates = [];

    if (remoteAbi) {
      candidates.push(new ethers.Contract(contractAddress, remoteAbi, connectedSigner));
    }
    candidates.push(new ethers.Contract(contractAddress, EXTRA_MINT_ABIS, connectedSigner));

    const overrideValue = process.env.MINT_VALUE_ETH
      ? ethers.parseEther(process.env.MINT_VALUE_ETH)
      : 0n;

    let walletSuccess = false;

    for (const contract of candidates) {
      const attempts = [];
      for (const qty of quantitiesToTry) {
        attempts.push(() => contract.mint({ value: overrideValue }));
        attempts.push(() => contract.mint(qty, { value: overrideValue }));
        attempts.push(() => contract.mint(wallet.address, { value: overrideValue }));
        attempts.push(() => contract.mint(wallet.address, qty, { value: overrideValue }));
        attempts.push(() => contract.publicMint({ value: overrideValue }));
        attempts.push(() => contract.publicMint(qty, { value: overrideValue }));
        attempts.push(() => contract.claim({ value: overrideValue }));
        attempts.push(() => contract.claim(qty, { value: overrideValue }));
        attempts.push(() => contract.claim(wallet.address, qty, { value: overrideValue }));
        attempts.push(() => contract.safeMint(wallet.address, { value: overrideValue }));
        attempts.push(() => contract.safeMint(wallet.address, qty, { value: overrideValue }));
        attempts.push(() => contract.mintNFT(qty, { value: overrideValue }));
        attempts.push(() => contract.mintPublic(qty, { value: overrideValue }));
      }

      for (const attempt of attempts) {
        try {
          const tx = await attempt();
          const receipt = await tx.wait();
          if (receipt.status === 1) {
            results.push(`✅ ${wallet.address.slice(0, 10)}... tx ${tx.hash.slice(0, 12)}...`);
            walletSuccess = true;
            anySuccess = true;
            break;
          }
        } catch (err) {
          continue;
        }
      }
      if (walletSuccess) break;
    }

    if (!walletSuccess) {
      results.push(`❌ ${wallet.address.slice(0, 10)}... failed`);
    }
  }

  let msg =
    `⚙️ <b>Direct mint fallback</b>\n` +
    `From: <code>${escapeHtml(sourceWallet)}</code>\n` +
    `Contract: <code>${escapeHtml(contractAddress)}</code>\n` +
    `Success: <b>${anySuccess ? 'yes' : 'no'}</b>\n\n` +
    results.join('\n');

  if (!anySuccess) {
    msg += `\n\n⚠️ Likely allowlist/signature or custom mint method.`;
  }

  await notify(msg);
}

function cleanOpenSeaError(msg) {
  const text = String(msg || '');

  // Keep short friendly labels for common cases
  if (text.includes('Drop not foun')) return 'Drop not found on OpenSea';
  if (text.includes('Wallet is not')) return 'Wallet not eligible';
  if (text.includes('404')) return 'OpenSea drop not found (404)';

  // For real debugging: show more of the original error
  return text
    .replace(/\s+/g, ' ')
    .slice(0, 300);
}

// ---------------------------------------------------------------------------
// Mint-copy pipeline
// ---------------------------------------------------------------------------

async function copyMint(contractAddress, sourceTxHash, sourceWallet, chainName = 'robinhood') {
    if (isPaused) {
    await notify(`⏸ Mint detected but bot is paused. Skipping.`);
    return;
  }

    const chain = chainConfigs[chainName] || chainConfigs.robinhood;
  const activeRpcPool =
    chainName === 'ethereum' ? ethRpcPool :
    chainName === 'ink' ? inkRpcPool :
    chainName === 'arc' ? arcRpcPool :
    rpcPool;
  const activeDryRun = chain.dryRun;
  const activeMaxPrice = chain.maxPriceEth;
  const activeOpenseaSlug = chain.openseaSlug;
  const chainLabel =
    chainName === 'ethereum' ? '🟦 ETH' :
    chainName === 'ink' ? '💜 INK' :
    chainName === 'arc' ? '🟧 ARC' :
    '🟢 RH';

  if (chainName === 'ethereum' && isEthPaused) {
  await notify(`⏸ ETH is paused. Skipping.`);
  return;
}
  if (chainName === 'ink' && isInkPaused) {
    await notify(`⏸ Ink is paused. Skipping.`);
    return;
}
  if (chainName === 'arc' && isArcPaused) {
    await notify(`⏸ Arc is paused. Skipping.`);
    return;
  }
if (chainName === 'robinhood' && isRhPaused) {
  await notify(`⏸ Robinhood is paused. Skipping.`);
  return;
}

  if (!activeRpcPool) {
    await notify(`${chainLabel} mint skipped: RPC pool not ready`);
    return;
  }

  const contractKey = contractAddress.toLowerCase();
  dailyStats.detected += 1;
  await saveDailyStats();

  console.log(`\n[mint detected] wallet=${sourceWallet} contract=${contractAddress} source_tx=${sourceTxHash}`);

  // Detect quantity
  let detectedQty = 1;
  try {
    const provider = activeRpcPool.current();
const receipt = await provider.getTransactionReceipt(sourceTxHash);
    if (receipt?.logs) {
      let count = 0;
      for (const log of receipt.logs) {
        if (
          log.topics.length >= 3 &&
          log.topics[0] === ERC721_TRANSFER_TOPIC &&
          log.topics[1] === ethers.zeroPadValue(NULL_ADDRESS, 32)
        ) {
          const toAddress = ('0x' + log.topics[2].slice(26)).toLowerCase();
          if (toAddress === sourceWallet.toLowerCase()) count++;
        }
      }
      if (count > 0) detectedQty = count;
    }
  } catch (err) {
    console.warn(`[mint] quantity detect failed: ${err.message}`);
  }

  // Quantity list
  let quantityTries = (process.env.QUANTITY_TRIES || '10,5,3,2,1')
    .split(',')
    .map(n => Number(n.trim()))
    .filter(n => n > 0);

  if (!quantityTries.includes(detectedQty)) quantityTries.push(detectedQty);
  quantityTries = [...new Set(quantityTries)].sort((a, b) => b - a);

  // Resolve collection
  let slug = null;
  try {
    slug = await resolveCollectionSlug(contractAddress, activeOpenseaSlug);
  } catch (err) {
    await notify(
      `🔔 <b>${chainLabel} Mint detected</b>\n` +
      `From: <code>${escapeHtml(sourceWallet)}</code>\n` +
      `Contract: <code>${escapeHtml(contractAddress)}</code>\n` +
      `⚠️ OpenSea lookup failed → trying direct mint`
    );
    return attemptDirectMint(contractAddress, sourceWallet, chainName);
  }

  if (!slug) {
    await notify(
      `🔔 <b>${chainLabel} Mint detected</b>\n` +
      `From: <code>${escapeHtml(sourceWallet)}</code>\n` +
      `Contract: <code>${escapeHtml(contractAddress)}</code>\n` +
      `⚠️ No OpenSea Drop found → trying direct mint`
    );
    return attemptDirectMint(contractAddress, sourceWallet, chainName);
  }

  // Initial summary message
  await notify(
    `🔔 <b>${chainLabel} Mint detected</b>\n` +
    `From: <code>${escapeHtml(sourceWallet)}</code>\n` +
    `Collection: <code>${escapeHtml(slug)}</code>\n` +
    `Detected qty: <b>${detectedQty}</b>\n` +
    `Trying quantities: <b>${quantityTries.join(', ')}</b>\n` +
    `Wallets: <b>${wallets.length || 1}</b>`
  );

  let targetWallets = activeDryRun
    ? [{ address: (wallets[0]?.address || WALLET_ADDRESS || ethers.ZeroAddress) }]
    : wallets;

  if (targetWallets.length === 0) {
    await notify(`❌ No minting wallets configured`);
    return;
  }

  // Skip wallets that already succeeded on this contract
  if (!activeDryRun) {
    const pending = targetWallets.filter((w) => {
      const key = `${contractKey}:${w.address.toLowerCase()}`;
      return !successfulMints.has(key);
    });

    if (pending.length === 0) {
      dailyStats.skipped += 1;
      await saveDailyStats();
      await notify(
        `⏭ <b>${chainLabel} skipped</b>\n` +
        `Contract: <code>${escapeHtml(contractAddress)}</code>\n` +
        `All minting wallets already succeeded on this collection.`
      );
      return;
    }

    if (pending.length < targetWallets.length) {
      await notify(
        `ℹ️ Retrying only <b>${pending.length}/${targetWallets.length}</b> wallets that have not succeeded yet.`
      );
    }

    targetWallets = pending;
  }

const useSponsor = isSponsorMode && sponsorWallet && !activeDryRun;

if (useSponsor) {
  console.log(`[sponsor] Using sponsor ${sponsorWallet.address} for ${targetWallets.length} wallets`);
}

dailyStats.attempted += 1;
await saveDailyStats();
let successCount = 0;
const results = [];

const mintOne = async (targetWallet) => {
  let walletSuccess = false;
  let lastError = '';

  for (const qty of quantityTries) {
    let raw;
    try {
      raw = await buildDropMintTransaction(slug, targetWallet.address, qty);
    } catch (err) {
  console.error('[opensea-error]', err.message || err);
  lastError = cleanOpenSeaError(err.message || 'OpenSea build failed');
  continue;
}

    const { to, data, value } = readMintTxFields(raw);
    if (!to || !data) {
      lastError = 'Invalid transaction data from OpenSea';
      continue;
    }

    const valueWei = BigInt(value || '0');
    const valueEth = Number(ethers.formatEther(valueWei));

    if (activeMaxPrice !== null && valueEth > activeMaxPrice) {
      lastError = `Price ${valueEth} ETH above limit`;
      continue;
    }

    if (activeDryRun) {
      results.push(`🧪 Dry run: would mint ${qty} → ${targetWallet.address.slice(0, 10)}... (${valueEth} ETH)`);
      walletSuccess = true;
      successCount++;
      break;
    }

    const payer = useSponsor ? sponsorWallet : targetWallet;
    const provider = activeRpcPool.current();
    const connectedSigner = payer.signer.connect(provider);

    try {
      const balance = await provider.getBalance(payer.address);
      const gasEstimate = await provider.estimateGas({
        to, data, value: valueWei, from: payer.address
      });
      const feeData = await provider.getFeeData();
      const gasPrice = feeData.maxFeePerGas ?? feeData.gasPrice ?? 0n;
      const totalCost = valueWei + gasEstimate * gasPrice;

      if (balance < totalCost) {
        lastError = `Insufficient balance on ${useSponsor ? 'sponsor' : 'wallet'} (need ~${ethers.formatEther(totalCost)} ETH)`;
        continue;
      }

      const tx = await connectedSigner.sendTransaction({ to, data, value: valueWei });
      const receipt = await tx.wait();

      if (receipt.status === 1) {
        results.push(
          `✅ ${targetWallet.address.slice(0, 10)}... received ${qty}` +
          (useSponsor ? ` (paid by sponsor)` : '') +
          ` | Tx: ${tx.hash.slice(0, 12)}...`
        );
        walletSuccess = true;
        successCount++;
        successfulMints.add(`${contractKey}:${targetWallet.address.toLowerCase()}`);
        dailyStats.success += 1;
        await saveDailyStats();
        break;
      } else {
        lastError = `Transaction reverted`;
      }
    } catch (err) {
      console.error('[mint-send-error]', err.message || err);
      lastError = cleanOpenSeaError(err.message || 'Send failed');
      continue;
    }
  }

  if (!walletSuccess) {
    results.push(`❌ ${targetWallet.address.slice(0, 10)}... failed → ${lastError.slice(0, 80)}`);
  }
};

  // Sequential: one wallet at a time (more consistent, less race)
  for (const targetWallet of targetWallets) {
    await mintOne(targetWallet);
  }

  // Final summary message
  let summary =
    `📋 <b>Result for</b> <code>${escapeHtml(slug)}</code>\n` +
    `Success: <b>${successCount}/${targetWallets.length}</b> wallets\n\n`;

  summary += results.join('\n');

  if (successCount === 0) {
    dailyStats.failed += 1;
    await saveDailyStats();
    summary += `\n\n⚠️ All OpenSea attempts failed. Trying direct mint fallback...`;
    await notify(summary);
    return attemptDirectMint(contractAddress, sourceWallet, chainName);
  }

  await notify(summary);
}

// ---------------------------------------------------------------------------
// Wallet watcher — polls every POLL_INTERVAL_MS
// ---------------------------------------------------------------------------

let lastCheckedBlock = null;
const seenTxHashes = new Set();

async function getLatestBlock() {
  return rpcPool.withFailover((p) => p.getBlockNumber());
}

async function findMintsInRange(fromBlock, toBlock) {
  const paddedNull = ethers.zeroPadValue(NULL_ADDRESS, 32);
  const logs = await rpcPool.withFailover((p) =>
    p.getLogs({ fromBlock, toBlock, topics: [ERC721_TRANSFER_TOPIC, paddedNull] })
  );

  const mints = [];
  for (const log of logs) {
    if (log.topics.length < 3) continue;
    const toAddress = ethers.getAddress('0x' + log.topics[2].slice(26)).toLowerCase();
    if (!watchedWallets.includes(toAddress)) continue;
    if (seenTxHashes.has(log.transactionHash)) continue;
    seenTxHashes.add(log.transactionHash);
    mints.push({ contractAddress: log.address, txHash: log.transactionHash, wallet: toAddress });
  }
  return mints;
}

async function pollLoop() {
  if (lastCheckedBlock === null) {
    lastCheckedBlock = await getLatestBlock();
    console.log(`[init] starting from block ${lastCheckedBlock}`);
  }

  try {
    const latest = await getLatestBlock();

    if (latest > lastCheckedBlock) {
      // Only check a limited number of blocks at a time (important fix)
      const MAX_BLOCKS_PER_SCAN = 1000;
      const toBlock = Math.min(lastCheckedBlock + MAX_BLOCKS_PER_SCAN, latest);

      console.log(`[poll] scanning blocks ${lastCheckedBlock + 1} → ${toBlock}`);

      const mints = await findMintsInRange(lastCheckedBlock + 1, toBlock);

      for (const mint of mints) {
        await copyMint(mint.contractAddress, mint.txHash, mint.wallet);
      }

      lastCheckedBlock = toBlock;
    }
  } catch (err) {
    console.error(`[poll] ${err.message}`);
  }

  setTimeout(pollLoop, POLL_INTERVAL_MS);
}

// ===== Ethereum watcher (Stage 2 Piece 1: detect only) =====
async function getEthLatestBlock() {
  if (!ethRpcPool) throw new Error('Ethereum RPC pool not initialized');
  return ethRpcPool.withFailover((p) => p.getBlockNumber());
}

async function findEthMintsInRange(fromBlock, toBlock) {
  const paddedNull = ethers.zeroPadValue(NULL_ADDRESS, 32);
  const logs = await ethRpcPool.withFailover((p) =>
    p.getLogs({
      fromBlock,
      toBlock,
      topics: [ERC721_TRANSFER_TOPIC, paddedNull],
    })
  );

  const mints = [];
  for (const log of logs) {
    if (log.topics.length < 3) continue;
    const toAddress = ethers.getAddress('0x' + log.topics[2].slice(26)).toLowerCase();
    if (!watchedWallets.includes(toAddress)) continue;
    if (ethSeenTxHashes.has(log.transactionHash)) continue;
    ethSeenTxHashes.add(log.transactionHash);
    mints.push({
      contractAddress: log.address,
      txHash: log.transactionHash,
      wallet: toAddress,
    });
  }
  return mints;
}

async function ethPollLoop() {
  if (!chainConfigs.ethereum.enabled || !ethRpcPool) return;

  try {
    const latest = await getEthLatestBlock();

    // Stay 2 blocks behind head to avoid public RPC errors
    const safeLatest = Math.max(latest - 2, 0);

    if (ethLastCheckedBlock === null) {
      ethLastCheckedBlock = safeLatest;
      console.log(`[eth-init] starting from block ${ethLastCheckedBlock}`);
    }

    if (safeLatest > ethLastCheckedBlock) {
      const MAX_BLOCKS_PER_SCAN = 200; // smaller range for public ETH RPC
      const toBlock = Math.min(ethLastCheckedBlock + MAX_BLOCKS_PER_SCAN, safeLatest);

      console.log(`[eth-poll] scanning blocks ${ethLastCheckedBlock + 1} → ${toBlock}`);

      const mints = await findEthMintsInRange(ethLastCheckedBlock + 1, toBlock);
      for (const mint of mints) {
  await copyMint(mint.contractAddress, mint.txHash, mint.wallet, 'ethereum');
}

      ethLastCheckedBlock = toBlock;
    }
  } catch (err) {
    console.error(`[eth-poll] ${err.message}`);
  }

  setTimeout(ethPollLoop, POLL_INTERVAL_MS);
}
// ===== End Ethereum watcher =====

// ===== Ink watcher =====
async function getInkLatestBlock() {
  if (!inkRpcPool) throw new Error('Ink RPC pool not initialized');
  return inkRpcPool.withFailover((p) => p.getBlockNumber());
}

async function findInkMintsInRange(fromBlock, toBlock) {
  const paddedNull = ethers.zeroPadValue(NULL_ADDRESS, 32);
  const logs = await inkRpcPool.withFailover((p) =>
    p.getLogs({
      fromBlock,
      toBlock,
      topics: [ERC721_TRANSFER_TOPIC, paddedNull],
    })
  );

  const mints = [];
  for (const log of logs) {
    if (log.topics.length < 3) continue;
    const toAddress = ethers.getAddress('0x' + log.topics[2].slice(26)).toLowerCase();
    if (!watchedWallets.includes(toAddress)) continue;
    if (inkSeenTxHashes.has(log.transactionHash)) continue;
    inkSeenTxHashes.add(log.transactionHash);
    mints.push({
      contractAddress: log.address,
      txHash: log.transactionHash,
      wallet: toAddress,
    });
  }
  return mints;
}

async function inkPollLoop() {
  if (!chainConfigs.ink.enabled || !inkRpcPool) return;

  try {
    const latest = await getInkLatestBlock();
    const safeLatest = Math.max(latest - 2, 0);

    if (inkLastCheckedBlock === null) {
      inkLastCheckedBlock = safeLatest;
      console.log(`[ink-init] starting from block ${inkLastCheckedBlock}`);
    }

    if (safeLatest > inkLastCheckedBlock) {
      const MAX_BLOCKS_PER_SCAN = 200;
      const toBlock = Math.min(inkLastCheckedBlock + MAX_BLOCKS_PER_SCAN, safeLatest);

      console.log(`[ink-poll] scanning blocks ${inkLastCheckedBlock + 1} → ${toBlock}`);

      const mints = await findInkMintsInRange(inkLastCheckedBlock + 1, toBlock);
      for (const mint of mints) {
        await copyMint(mint.contractAddress, mint.txHash, mint.wallet, 'ink');
      }

      inkLastCheckedBlock = toBlock;
    }
  } catch (err) {
    console.error(`[ink-poll] ${err.message}`);
  }

  setTimeout(inkPollLoop, POLL_INTERVAL_MS);
}
// ===== End Ink watcher =====

// ===== Arc watcher =====
async function getArcLatestBlock() {
  if (!arcRpcPool) throw new Error('Arc RPC pool not initialized');
  return arcRpcPool.withFailover((p) => p.getBlockNumber());
}

async function findArcMintsInRange(fromBlock, toBlock) {
  const paddedNull = ethers.zeroPadValue(NULL_ADDRESS, 32);
  const logs = await arcRpcPool.withFailover((p) =>
    p.getLogs({
      fromBlock,
      toBlock,
      topics: [ERC721_TRANSFER_TOPIC, paddedNull],
    })
  );

  const mints = [];
  for (const log of logs) {
    if (log.topics.length < 3) continue;
    const toAddress = ethers.getAddress('0x' + log.topics[2].slice(26)).toLowerCase();
    if (!watchedWallets.includes(toAddress)) continue;
    if (arcSeenTxHashes.has(log.transactionHash)) continue;
    arcSeenTxHashes.add(log.transactionHash);
    mints.push({
      contractAddress: log.address,
      txHash: log.transactionHash,
      wallet: toAddress,
    });
  }
  return mints;
}

async function arcPollLoop() {
  if (!chainConfigs.arc.enabled || !arcRpcPool) {
    console.warn('[arc-poll] skipped: enabled or rpcPool missing');
    return;
  }

  try {
    const latest = await getArcLatestBlock();
    const safeLatest = Math.max(latest - 2, 0);

    if (arcLastCheckedBlock === null) {
      arcLastCheckedBlock = safeLatest;
      console.log(`[arc-init] starting from block ${arcLastCheckedBlock}`);
    }

    if (safeLatest > arcLastCheckedBlock) {
      const MAX_BLOCKS_PER_SCAN = 200;
      const toBlock = Math.min(arcLastCheckedBlock + MAX_BLOCKS_PER_SCAN, safeLatest);

      console.log(`[arc-poll] scanning blocks ${arcLastCheckedBlock + 1} → ${toBlock}`);

      const mints = await findArcMintsInRange(arcLastCheckedBlock + 1, toBlock);
      for (const mint of mints) {
        await copyMint(mint.contractAddress, mint.txHash, mint.wallet, 'arc');
      }

      arcLastCheckedBlock = toBlock;
    }
  } catch (err) {
    console.error(`[arc-poll] ${err.message}`);
  }

  setTimeout(arcPollLoop, POLL_INTERVAL_MS);
}
// ===== End Arc watcher =====

// ---------------------------------------------------------------------------
// Startup
// ---------------------------------------------------------------------------

async function main() {
  console.log(`[startup] config: chain=${CHAIN_ID} DRY_RUN=${DRY_RUN} rpcs=${RPC_URLS.length} pollMs=${POLL_INTERVAL_MS}`);

  console.log('[startup] refreshing watched wallets from Supabase...');
  await withTimeout(refreshWatchedWallets(), 15000, 'Supabase initial wallet load');
  console.log(`[startup] loaded ${watchedWallets.length} watched wallet(s)`);
  console.log('[startup] loading daily stats from Supabase...');
  await loadDailyStats();
  setInterval(refreshWatchedWallets, WALLET_REFRESH_MS);

  console.log('[startup] launching Telegram bot (long-poll)...');
  // bot.launch() intentionally never resolves in polling mode until stopped —
  // don't await it, or the rest of startup never runs. Catch async errors instead.
  bot.launch().catch((err) => console.error('[telegram] launch error:', err));
  console.log('[telegram] bot launch initiated');

 await notify(
  `🤖 <b>Bot started</b>\n` +
  `Watched wallets: <b>${watchedWallets.length}</b>\n` +
  `Poll: <b>${POLL_INTERVAL_MS}ms</b>\n\n` +
  `🟢 Robinhood: <b>${chainConfigs.robinhood.enabled ? 'ON' : 'OFF'}</b> (dryRun=${chainConfigs.robinhood.dryRun})\n` +
  `🟦 Ethereum: <b>${chainConfigs.ethereum.enabled ? 'ON' : 'OFF'}</b> (dryRun=${chainConfigs.ethereum.dryRun})\n` +
  `💜 Ink: <b>${chainConfigs.ink.enabled ? 'ON' : 'OFF'}</b> (dryRun=${chainConfigs.ink.dryRun})\n` +
  `⬜ ARC: <b>${chainConfigs.arc.enabled ? 'ON' : 'OFF'}</b> (dryRun=${chainConfigs.arc.dryRun})\n\n` +
  `Stage 1: multi-chain foundation loaded.\n` +
  `Robinhood minting still active as before.`
);
  console.log('[startup] Telegram notify sent, entering poll loop');

  pollLoop();
  if (chainConfigs.ethereum.enabled && ethRpcPool) {
  console.log('[startup] starting Ethereum poll loop...');
  ethPollLoop();
}
  if (chainConfigs.ink.enabled && inkRpcPool) {
    console.log('[startup] starting Ink poll loop...');
    inkPollLoop();
  }
  
  console.log(
    `[startup] Arc check: enabled=${chainConfigs.arc.enabled} rpcPool=${arcRpcPool ? 'yes' : 'no'} rpcs=${chainConfigs.arc.rpcUrls.length}`
  );
  if (chainConfigs.arc.enabled && arcRpcPool) {
    console.log('[startup] starting Arc poll loop...');
    arcPollLoop();
  } else {
    console.warn('[startup] Arc poll loop NOT started');
  }
  // Daily summary at 20:00 UTC every day
  function msUntilNext8pmUTC() {
    const now = new Date();
    const next = new Date(Date.UTC(
      now.getUTCFullYear(),
      now.getUTCMonth(),
      now.getUTCDate(),
      20, 0, 0, 0 // 20:00 UTC = 8:00 PM UTC
    ));
    if (next <= now) {
      next.setUTCDate(next.getUTCDate() + 1);
    }
    return next.getTime() - now.getTime();
  }

  async function sendDailySummary() {
    const msg =
      `📊 <b>Daily Summary</b>\n\n` +
      `Detected: <b>${dailyStats.detected}</b>\n` +
      `Attempted: <b>${dailyStats.attempted}</b>\n` +
      `Success: <b>${dailyStats.success}</b>\n` +
      `Failed: <b>${dailyStats.failed}</b>\n` +
      `Skipped: <b>${dailyStats.skipped}</b>`;

    await notify(msg);
    resetDailyStats();
  }

  function scheduleDailySummary() {
    const delay = msUntilNext8pmUTC();
    console.log(`[startup] Next daily summary in ${Math.round(delay / 60000)} minutes (20:00 UTC)`);
    setTimeout(async () => {
      await sendDailySummary();
      setInterval(sendDailySummary, 24 * 60 * 60 * 1000);
    }, delay);
  }

  scheduleDailySummary();
}

process.once('SIGINT', () => bot.stop('SIGINT'));
process.once('SIGTERM', () => bot.stop('SIGTERM'));

main().catch((err) => {
  console.error('Fatal error:', err);
  process.exit(1);
});
